### ISSUE TITLE
Tests fail with "ImportError: No module named multibackend"

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#1074]
```
--- git/pixelated-user-agent ‹master› » vagrant up
...

==> source: Notice: /Stage[main]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: executed successfully
==> source: Notice: Finished catalog run in 516.76 seconds

--- git/pixelated-user-agent ‹master› » vagrant ssh
Development Environment
(pixua)vagrant@leap-jessie:/vagrant$ make functional_tests
rm -rf service/_trial_temp
find . -name "*.pyc" -delete
rm -rf service/.coverage
rm -rf service/htmlcov
rm -rf web-ui/dist
rm -rf web-ui/.sass-cache
rm -rf ~/.config/leap
rm -rf ~/.leap
rm -rf service/ghostdriver.log
Requirement already up-to-date: pip in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages
Requirement already up-to-date: setuptools in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages
Requirement already up-to-date: packaging>=16.8 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: appdirs>=1.4.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: six>=1.6.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: pyparsing in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from packaging>=16.8->setuptools)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pysqlcipher
  Using cached pysqlcipher-2.6.10.tar.gz
Installing collected packages: pysqlcipher
  Found existing installation: pysqlcipher 2.6.10
    Uninstalling pysqlcipher-2.6.10:
      Successfully uninstalled pysqlcipher-2.6.10
  Running setup.py install for pysqlcipher ... done
Successfully installed pysqlcipher-2.6.10
Obtaining file:///vagrant/service (from -r requirements.txt (line 13))
Obtaining gnupg from git+https://github.com/pixelated/python-gnupg.git@develop#egg=gnupg (from -r requirements.txt (line 3))
  Updating /home/vagrant/.venvs/pixua/src/gnupg clone (to develop)
Requirement already satisfied: pyasn1==0.1.9 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests==2.11.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: srp==1.0.6 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: whoosh==2.6.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: Twisted==16.1.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Obtaining leap.common from git+https://0xacab.org/leap/leap_pycommon.git@master#egg=leap.common (from -r requirements.txt (line 9))
  Updating /home/vagrant/.venvs/pixua/src/leap.common clone (to master)
Obtaining leap.bitmask from git+https://0xacab.org/pixelated/bitmask-dev.git@development#egg=leap.bitmask (from -r requirements.txt (line 10))
  Updating /home/vagrant/.venvs/pixua/src/leap.bitmask clone (to development)
Obtaining leap.soledad.common from git+https://0xacab.org/pixelated/soledad.git@development#egg=leap.soledad.common&subdirectory=common/ (from -r requirements.txt (line 11))
  Updating /home/vagrant/.venvs/pixua/src/leap.soledad.common clone (to development)
Obtaining leap.soledad.client from git+https://0xacab.org/pixelated/soledad.git@development#egg=leap.soledad.client&subdirectory=client/ (from -r requirements.txt (line 12))
  Updating /home/vagrant/.venvs/pixua/src/leap.soledad.client clone (to development)
Requirement already satisfied: behave==1.2.5 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 1))
Requirement already satisfied: selenium==3.0.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 2))
Requirement already satisfied: mock==2.0.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 3))
Requirement already satisfied: httmock==1.2.2 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 4))
Requirement already satisfied: mockito==0.5.2 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 5))
Requirement already satisfied: funkload==1.16.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 6))
Requirement already satisfied: pep8==1.5.7 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 7))
Requirement already satisfied: tempdir==0.6 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 8))
Requirement already satisfied: coverage in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 9))
Requirement already satisfied: crochet==1.4.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 10))
Requirement already satisfied: poster==0.8.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 11))
Requirement already satisfied: locustio==0.7.3 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from -r test_requirements.txt (line 12))
Requirement already satisfied: psutil>=1.2.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from gnupg->-r requirements.txt (line 3))
Requirement already satisfied: zope.interface>=3.6.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from Twisted==16.1.1->-r requirements.txt (line 8))
Requirement already satisfied: jsonschema in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.common->-r requirements.txt (line 9))
Requirement already satisfied: pyopenssl in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.common->-r requirements.txt (line 9))
Requirement already satisfied: python-dateutil in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.common->-r requirements.txt (line 9))
Requirement already satisfied: pyzmq>=14.4.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.common->-r requirements.txt (line 9))
Requirement already satisfied: txzmq>=0.7.3 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.common->-r requirements.txt (line 9))
Requirement already satisfied: service-identity in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.bitmask->-r requirements.txt (line 10))
Requirement already satisfied: colorama in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.bitmask->-r requirements.txt (line 10))
Requirement already satisfied: paste in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.common->-r requirements.txt (line 11))
Requirement already satisfied: routes in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.common->-r requirements.txt (line 11))
Requirement already satisfied: pysqlcipher>2.6.3 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: scrypt in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: zope.proxy in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: cryptography in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: six in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from behave==1.2.5->-r test_requirements.txt (line 1))
Requirement already satisfied: parse>=1.6.3 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from behave==1.2.5->-r test_requirements.txt (line 1))
Requirement already satisfied: parse-type>=0.3.4 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from behave==1.2.5->-r test_requirements.txt (line 1))
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from mock==2.0.0->-r test_requirements.txt (line 3))
Requirement already satisfied: pbr>=0.11 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from mock==2.0.0->-r test_requirements.txt (line 3))
Requirement already satisfied: webunit>=1.3.8 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: docutils>=0.3.7 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: setuptools in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: gevent>=1.0.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: flask>=0.10.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: msgpack-python>=0.4.2 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: functools32; python_version == "2.7" in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from jsonschema->leap.common->-r requirements.txt (line 9))
Requirement already satisfied: attrs in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from service-identity->leap.bitmask->-r requirements.txt (line 10))
Requirement already satisfied: pyasn1-modules in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from service-identity->leap.bitmask->-r requirements.txt (line 10))
Requirement already satisfied: repoze.lru>=0.3 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from routes->leap.soledad.common->-r requirements.txt (line 11))
Requirement already satisfied: idna>=2.1 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: asn1crypto>=0.21.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: enum34 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: ipaddress in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: cffi>=1.7 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: packaging>=16.8 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from setuptools->funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: appdirs>=1.4.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from setuptools->funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: greenlet>=0.4.10 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from gevent>=1.0.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: itsdangerous>=0.21 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from flask>=0.10.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: Jinja2>=2.4 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from flask>=0.10.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: Werkzeug>=0.7 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from flask>=0.10.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: click>=2.0 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from flask>=0.10.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Requirement already satisfied: pycparser in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from cffi>=1.7->cryptography->leap.soledad.client->-r requirements.txt (line 12))
Requirement already satisfied: pyparsing in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from packaging>=16.8->setuptools->funkload==1.16.1->-r test_requirements.txt (line 6))
Requirement already satisfied: MarkupSafe>=0.23 in /home/vagrant/.venvs/pixua/lib/python2.7/site-packages (from Jinja2>=2.4->flask>=0.10.1->locustio==0.7.3->-r test_requirements.txt (line 12))
Installing collected packages: gnupg, leap.common, leap.bitmask, leap.soledad.common, leap.soledad.client, pixelated-user-agent
  Found existing installation: gnupg 2.0.2-79-gd34e96a
    Uninstalling gnupg-2.0.2-79-gd34e96a:
      Successfully uninstalled gnupg-2.0.2-79-gd34e96a
  Running setup.py develop for gnupg
  Found existing installation: leap.common 0.5.5
    Uninstalling leap.common-0.5.5:
      Successfully uninstalled leap.common-0.5.5
  Running setup.py develop for leap.common
  Found existing installation: leap.bitmask 0.9.3+368.g940a793
    Uninstalling leap.bitmask-0.9.3+368.g940a793:
      Successfully uninstalled leap.bitmask-0.9.3+368.g940a793
  Running setup.py develop for leap.bitmask
  Found existing installation: leap.soledad.common 0.9.2+104.g00148b3
    Uninstalling leap.soledad.common-0.9.2+104.g00148b3:
      Successfully uninstalled leap.soledad.common-0.9.2+104.g00148b3
  Running setup.py develop for leap.soledad.common
  Found existing installation: leap.soledad.client 0.9.2+104.g00148b3
    Uninstalling leap.soledad.client-0.9.2+104.g00148b3:
      Successfully uninstalled leap.soledad.client-0.9.2+104.g00148b3
  Running setup.py develop for leap.soledad.client
  Found existing installation: pixelated-user-agent 0.1
    Uninstalling pixelated-user-agent-0.1:
      Successfully uninstalled pixelated-user-agent-0.1
  Running setup.py develop for pixelated-user-agent
Successfully installed gnupg leap.bitmask leap.common leap.soledad.client leap.soledad.common pixelated-user-agent

> node-sass@4.5.0 install /vagrant/web-ui/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /vagrant/web-ui/node_modules/node-sass/vendor/linux-x64-51/binding.node

> node-sass@4.5.0 postinstall /vagrant/web-ui/node_modules/node-sass
> node scripts/build.js

Binary found at /vagrant/web-ui/node_modules/node-sass/vendor/linux-x64-51/binding.node
Testing binary
Binary is fine
node-sass@4.5.0 /vagrant/web-ui/node_modules/node-sass

> pixelated-user-agent-web-ui@0.0.0 build /vagrant/web-ui
> npm run build:statics && npm run build:js


> pixelated-user-agent-web-ui@0.0.0 build:statics /vagrant/web-ui
> npm run clean && npm run build:handlebars && npm run add_git_version && npm run build:compass


> pixelated-user-agent-web-ui@0.0.0 clean /vagrant/web-ui
> rm -rf app/js/generated/hbs/* app/css/*


> pixelated-user-agent-web-ui@0.0.0 build:handlebars /vagrant/web-ui
> mkdir -p app/js/generated/hbs/ && handlebars app/templates/**/*.hbs > app/js/generated/hbs/templates.js --namespace=window.Pixelated --root .


> pixelated-user-agent-web-ui@0.0.0 add_git_version /vagrant/web-ui
> /bin/bash config/add_git_version.sh


> pixelated-user-agent-web-ui@0.0.0 build:compass /vagrant/web-ui
> compass compile

    write app/css/sandbox.css
    write app/css/style.css

> pixelated-user-agent-web-ui@0.0.0 build:js /vagrant/web-ui
> webpack --colors --progress

Hash: 74a74a35fe8046dc114bc3cd0c9c9dac5ae3fcf2
Version: webpack 1.14.0
Child
    Hash: 74a74a35fe8046dc114b
    Version: webpack 1.14.0
    Time: 20375ms
                                              Asset       Size  Chunks             Chunk Names
                          fonts/OpenSans-Light.woff      15 kB          [emitted]  
               674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]  
              fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]  
               b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]  
               912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  
                                account_recovery.js    1.66 MB       0  [emitted]  account_recovery
                                           login.js    1.36 MB       1  [emitted]  login
                            account_recovery.js.map    1.97 MB       0  [emitted]  account_recovery
                                       login.js.map    1.64 MB       1  [emitted]  login
                      _login_disclaimer_banner.html  239 bytes          [emitted]  
                                         login.html  950 bytes          [emitted]  
                                          login.css    1.65 kB          [emitted]  
                                  normalize.min.css       2 kB          [emitted]  
                                       opensans.css    2.03 kB          [emitted]  
                              account_recovery.html  482 bytes          [emitted]  
                                  interstitial.html  603 bytes          [emitted]  
                                    interstitial.js    1.65 kB          [emitted]  
                                jquery-2.1.3.min.js    84.3 kB          [emitted]  
                                    snap.svg-min.js    73.2 kB          [emitted]  
                                  fonts/icomoon.ttf    1.27 kB          [emitted]  
                                 fonts/icomoon.woff    1.35 kB          [emitted]  
                           fonts/OpenSans-Bold.woff    14.5 kB          [emitted]  
                     fonts/OpenSans-BoldItalic.woff    15.5 kB          [emitted]  
                      fonts/OpenSans-Extrabold.woff    15.3 kB          [emitted]  
                fonts/OpenSans-ExtraboldItalic.woff    15.9 kB          [emitted]  
                         fonts/OpenSans-Italic.woff    15.8 kB          [emitted]  
             af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]  
                       fonts/OpenSans-Semibold.woff    15.2 kB          [emitted]  
                 fonts/OpenSans-SemiboldItalic.woff    15.7 kB          [emitted]  
                                fonts/OpenSans.woff    14.6 kB          [emitted]  
                    fonts/OpenSansLight-Italic.woff      16 kB          [emitted]  
                     locales/en_US/translation.json    6.25 kB          [emitted]  
                     locales/pt_BR/translation.json    6.71 kB          [emitted]  
                     locales/sv_SE/translation.json    1.44 kB          [emitted]  
         images/account-recovery/admins_contact.svg    23.9 kB          [emitted]  
                  images/account-recovery/codes.svg    7.18 kB          [emitted]  
                 images/account-recovery/step_1.svg    15.8 kB          [emitted]  
                 images/account-recovery/step_2.svg    20.7 kB          [emitted]  
                 images/account-recovery/step_3.svg    20.7 kB          [emitted]  
                 images/account-recovery/step_4.svg    20.6 kB          [emitted]  
                               images/dead-mail.svg    8.84 kB          [emitted]  
                                 images/fa-sent.svg    2.42 kB          [emitted]  
                                 images/favicon.png  592 bytes          [emitted]  
                      images/forgot-my-password.svg    38.6 kB          [emitted]  
                                 images/hive-bg.png    3.36 kB          [emitted]  
                                     images/lab.svg    6.82 kB          [emitted]  
                     images/LOADING-transparent.gif    16.2 kB          [emitted]  
                             images/logo-orange.svg     2.5 kB          [emitted]  
                                    images/logo.svg    2.53 kB          [emitted]  
                            images/message sent.svg    5.92 kB          [emitted]  
    images/pixelated-symbol-blue-transparent-01.png    9.07 kB          [emitted]  
                               images/sent-mail.svg    5.62 kB          [emitted]  
                                 images/welcome.svg    41.4 kB          [emitted]  
        + 567 hidden modules
Child
    Hash: c3cd0c9c9dac5ae3fcf2
    Version: webpack 1.14.0
    Time: 20534ms
                                     Asset       Size  Chunks             Chunk Names
             fonts/fontawesome-webfont.eot      56 kB          [emitted]  
      674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]  
     fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]  
      b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]  
      912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  
                                    app.js     634 kB       0  [emitted]  app
                                    1.1.js    2.33 kB       1  [emitted]  
                         backup_account.js    1.69 MB       2  [emitted]  backup_account
                                sandbox.js    1.78 kB       3  [emitted]  sandbox
                                app.js.map     910 kB       0  [emitted]  app
                                1.1.js.map    3.25 kB       1  [emitted]  
                     backup_account.js.map    2.01 MB       2  [emitted]  backup_account
                            sandbox.js.map    2.16 kB       3  [emitted]  sandbox
                                  404.html    4.46 kB          [emitted]  
                                index.html    5.56 kB          [emitted]  
                              sandbox.html  260 bytes          [emitted]  
                           css/sandbox.css  547 bytes          [emitted]  
                             css/style.css    73.5 kB          [emitted]  
                     account_recovery.html  482 bytes          [emitted]  
                       backup_account.html  480 bytes          [emitted]  
    af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]  
             fonts/fontawesome-webfont.ttf     112 kB          [emitted]  
            fonts/fontawesome-webfont.woff    65.5 kB          [emitted]  
             fonts/fontawesome-webfont.svg     287 kB          [emitted]  
                     fonts/FontAwesome.otf    85.9 kB          [emitted]  
                  css/font-awesome.min.css      22 kB          [emitted]  
                 css/jquery.fileupload.css  674 bytes          [emitted]  
                              modernizr.js    51.4 kB          [emitted]  
                             lodash.min.js    28.2 kB          [emitted]  
                             jquery.min.js    84.3 kB          [emitted]  
                          jquery-ui.min.js     240 kB          [emitted]  
                      jquery.fileupload.js    63.7 kB          [emitted]  
                         handlebars.min.js    72.6 kB          [emitted]  
                   typeahead.bundle.min.js    29.7 kB          [emitted]  
                      iframeResizer.min.js    11.8 kB          [emitted]  
        iframeResizer.contentWindow.min.js    13.5 kB          [emitted]  
                             foundation.js     187 kB          [emitted]  
                      foundation.reveal.js    14.1 kB          [emitted]  
                   foundation.offcanvas.js    5.81 kB          [emitted]  
                  initialize_foundation.js   63 bytes          [emitted]  
        + 659 hidden modules
Exception ImportError: No module named multibackend
Traceback (most recent call last):
  File "/home/vagrant/.venvs/pixua/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/behave/runner.py", line 677, in run_with_paths
    self.load_hooks()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/behave/runner.py", line 631, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/behave/runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "test/functional/features/environment.py", line 27, in <module>
    from pixelated.application import UserAgentMode
  File "/vagrant/service/pixelated/application.py", line 32, in <module>
    from pixelated.adapter.welcome_mail import add_welcome_mail
  File "/vagrant/service/pixelated/adapter/welcome_mail.py", line 18, in <module>
    from pixelated.adapter.model.mail import InputMail
  File "/vagrant/service/pixelated/adapter/model/mail.py", line 26, in <module>
    from leap.bitmask.mail import walk
  File "/home/vagrant/.venvs/pixua/src/leap.bitmask/src/leap/bitmask/mail/walk.py", line 23, in <module>
    from cryptography.hazmat.backends.multibackend import MultiBackend
ImportError: No module named multibackend
Makefile:80: recipe for target 'functional_tests' failed
make: *** [functional_tests] Error 1

```

**Comment by varac** [comment]
I noticed that all tests fail because of the missing module, not only the functional tests.

**Comment by varac** [comment]
circle CI fails with the same issue: https://circleci.com/gh/pixelated/pixelated-user-agent/236

**Comment by tuliocasagrande** [comment]
According to https://cryptography.io/en/stable/changelog/, version 1.9 (2017-05-29) removed MultiBackend.
For now, we can stick to version 1.8.2.

**Comment by deniscostadsc** [comment]
We [created a issue](https://0xacab.org/leap/bitmask-dev/issues/8910) on Bitmask for this problem. Closing this issue.
