### ISSUE TITLE
tell the user if connection to leap platform failed

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#163]
I get a 404 if the connection to example.wazokazi.is is not up.
Maybe we should tell the user that something went wrong on the platform:

2014-11-26 15:23:44+0000 [-] urllib3.connectionpool: INFO     Starting new HTTPS connection (1): api.example.wazokazi.is
2014-11-26 15:23:59+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 136, in <lambda>
	    reactor.callWhenRunning(lambda: init_app(app))
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 98, in init_app
	    leap_session = init_leap_session(app)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 87, in init_leap_session
	    app.config['LEAP_SERVER_NAME'])
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 120, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 138, in _create_new_session
	    smtp.start()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/smtp.py", line 75, in start
	    self._download_client_certificates()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/smtp.py", line 59, in _download_client_certificates
	    response = requests.get(cert_url, verify=which_bundle(self._provider), cookies=cookies, timeout=self._provider.config.timeout_in_s)
	  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
	    return request('get', url, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
	    return session.request(method=method, url=url, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
	    resp = self.send(prep, **send_kwargs)
	  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
	    r = adapter.send(request, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 422, in send
	    raise ReadTimeout(e, request=request)
	requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.example.wazokazi.is', port=4430): Read timed out. (read timeout=15)

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
