### ISSUE TITLE
Display a sane error if soledad can't find the mailbox on mail creation

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#193]
```
2014-12-15 14:29:13+0000 [HTTPChannel,263,172.17.42.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
            body = resrc.render(self)
          File "/usr/lib/python2.7/dist-packages/klein/resource.py", line 124, in render
            d = defer.maybeDeferred(_execute)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib/python2.7/dist-packages/klein/resource.py", line 118, in _execute
            **kwargs)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 100, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 185, in _f
            return _call(instance, f, request, *a, **kw)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 27, in _call
            return f(*args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/pixelated/controllers/mails_controller.py", line 122, in update_draft
            ident = self._draft_service.create_draft(_mail).ident
          File "/usr/lib/python2.7/dist-packages/pixelated/adapter/draft_service.py", line 10, in create_draft
            self._drafts().add(input_mail)
          File "/usr/lib/python2.7/dist-packages/pixelated/adapter/mailbox.py", line 42, in add
            return self.querier.create_mail(mail, self.mailbox_name)
          File "/usr/lib/python2.7/dist-packages/pixelated/adapter/soledad_querier.py", line 105, in create_mail
            mbox = [m for m in self.soledad.get_from_index('by-type', 'mbox') if m.content['mbox'] == 'INBOX'][0]
        exceptions.IndexError: list index out of range


```

**Comment by dudadornelles** [comment]
The problem here is that we were getting the uid always from the INBOX probably because initially we were using the uid as unique id instead of the chash. Always getting the uid from the same mailbox would make it unique. Now since we are using the chash there is no need to do that.

With this change we will get the UID from the mailbox it is being added on. That mailbox will be created for sure given the way we are initialising mailboxes (adapter/services/mailboxes.py#28:33)
