### ISSUE TITLE
Error when there are special characters in the subject 

### ISSUE THREAD

**Issue by that-luiz** [pixelated/pixelated-user-agent#360]
Get an error message when I attempt to send an email with special chars on the subject (such as á, é, or ú).  Email is sent anyway.

![screen shot 2015-04-07 at 8 11 52 pm](https://cloud.githubusercontent.com/assets/1223531/7035882/0547381c-dd64-11e4-88d1-eaa65deaad3f.png)

**Comment by fbernitt** [comment]
Stracktrace no longer shows up in user agent, but in the agent logs we found this exception when trying a subject with umlauts:

```
2015-09-01 08:26:41 [twisted] INFO Connecting to SMTP server unstable1.unstable.pixelated-project.org:465
2015-09-01 08:26:41 [twisted] INFO Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x538f248>
something failed
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/vagrant/service/pixelated/adapter/services/mail_service.py", line 85, in send_mail
    sent_mail = yield self.move_to_sent(draft_id, mail)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/vagrant/service/pixelated/adapter/services/mail_service.py", line 92, in move_to_sent
    sent_mail = yield self.mail_store.add_mail('SENT', mail.raw)
  File "/vagrant/service/pixelated/adapter/model/mail.py", line 126, in raw
    return self._mime_multipart.as_string()
  File "/vagrant/service/pixelated/adapter/model/mail.py", line 101, in _mime_multipart
    mime[str(key)] = str(value)
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)

2015-09-01 08:26:41 [twisted] CRITICAL something failed
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/vagrant/service/pixelated/adapter/services/mail_service.py", line 85, in send_mail
    sent_mail = yield self.move_to_sent(draft_id, mail)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/vagrant/service/pixelated/adapter/services/mail_service.py", line 92, in move_to_sent
    sent_mail = yield self.mail_store.add_mail('SENT', mail.raw)
  File "/vagrant/service/pixelated/adapter/model/mail.py", line 126, in raw
    return self._mime_multipart.as_string()
  File "/vagrant/service/pixelated/adapter/model/mail.py", line 101, in _mime_multipart
    mime[str(key)] = str(value)
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)

2015-09-01 08:26:41 [twisted] INFO "10.0.2.2" - - [01/Sep/2015:08:26:41 +0000] "POST /mails HTTP/1.1" 422 46 "http://localhost:3333/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36"
2015-09-01 08:26:41 [twisted] INFO Stopping factory <twisted.mail.smtp.SMTPSenderFactory instance at 0x5392f38>
2015-09-01 08:26:42 [twisted] INFO Message sent to <fbernitt@thoughtworks.com>
```
