### ISSUE TITLE
List mails using new data model

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#426]
## Note
This issue is part of #420

**Comment by neissi** [comment]
I created a new account, and when a run the user-agent a got this exception:

2015-08-24 16:27:59 [twisted] INFO Deleting Incoming message: 1a5fd4af-4113-4f65-8996-beef706e467d
Unhandled Error
Traceback (most recent call last):
  File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 859, in _cbDeferred
    self.callback(self.resultList)
  File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/nlima/dev/pixelated-user-agent/.venv/src/leap.mail/src/leap/mail/imap/mailbox.py", line 397, in cbNotifyNew
    listener.newMessages(exists, recent)
  File "/Users/nlima/dev/pixelated-user-agent/service/pixelated/adapter/listeners/mailbox_indexer_listener.py", line 41, in newMessages
    missing_idents = soledad_idents.difference(indexed_idents)
exceptions.AttributeError: Deferred instance has no attribute 'difference'

**Comment by shyba** [comment]
Issue #439 opened for that. It is unrelated to listing, this happens when a new mail arrives. The mailboxIndexer tries to index the incoming mail and explodes. It is not migrated yet.

**Comment by neissi** [comment]
@shyba Thanks for clarify.
