### ISSUE TITLE
Migrate MailboxIndexer to new data model

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#439]
It is still using old soledad_querier and raising errors. Still, it should be easy to fix.
From: #423 and #426 
Traceback
=================
```
2015-08-24 16:27:59 [twisted] INFO Deleting Incoming message: 1a5fd4af-4113-4f65-8996-beef706e467d
Unhandled Error
Traceback (most recent call last):
File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
current.result = callback(current.result, args, *kw)
File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 859, in _cbDeferred
self.callback(self.resultList)
File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
self._startRunCallbacks(result)
File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
self._runCallbacks()
--- ---
File "/Users/nlima/dev/pixelated-user-agent/.venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
current.result = callback(current.result, args, *kw)
File "/Users/nlima/dev/pixelated-user-agent/.venv/src/leap.mail/src/leap/mail/imap/mailbox.py", line 397, in cbNotifyNew
listener.newMessages(exists, recent)
File "/Users/nlima/dev/pixelated-user-agent/service/pixelated/adapter/listeners/mailbox_indexer_listener.py", line 41, in newMessages
missing_idents = soledad_idents.difference(indexed_idents)
exceptions.AttributeError: Deferred instance has no attribute 'difference'
```

Definition of done:
Receive a mail (from anywhere) without restarting the client and see it indexed and showing as new without errors.

**Comment by shyba** [comment]
Adding listener to leap.mail will go to bootstrap code as discussed today.

**Comment by shyba** [comment]
done, retested. :+1:
