### ISSUE TITLE
pixelated-register broken on try

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#455]
the try pipeline can not create accounts anymore. 
The pixelated-register tool breaks:
'''
13:04:26.573 2015-09-10 13:04:27 [leap.soledad.client.secrets] INFO Trying to fetch cryptographic secrets from shared recovery database...
13:04:27.132 Exception in thread Thread-1:
13:04:27.132 Traceback (most recent call last):
13:04:27.133   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
13:04:27.133     self.run()
13:04:27.133   File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 457, in run
13:04:27.133     self._init_zmq()
13:04:27.134   File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 297, in _init_zmq
13:04:27.134     self._sub = self._zmq_connect_sub()
13:04:27.134   File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 344, in _zmq_connect_sub
13:04:27.134     stream = self._zmq_connect(zmq.SUB, self._reg_addr)
13:04:27.135   File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 320, in _zmq_connect
13:04:27.135     server_public, _ = zmq.auth.load_certificate(server_public_file)
13:04:27.135   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/zmq/auth/certs.py", line 91, in load_certificate
13:04:27.135     raise IOError("Invalid certificate file: {0}".format(filename))
13:04:27.136 IOError: Invalid certificate file: /root/.config/leap/events/zmq_certificates/public_keys/server.key
'''

**Comment by cz8s** [comment]
the client.key gets downloaded and is placed in /root/.config/leap/events/zmq_certificates/public_keys/
server.key is missing. After running pixelated-user-agent it is there.

**Comment by cz8s** [comment]
pixelated-register was not ported to the new libs i think. it doesn't use any twisted yet?
