### ISSUE TITLE
Analyse flaky functional tests

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#456]
Our functional tests are really flaky and slow. The goal of this issue is to identify and fix slow or flaky parts in a two day timebox. If problems are identified that do not fit into this timeframe, create new issues.

**Comment by fbernitt** [comment]
Overall test execution speed got a lot faster, problem at the moment are mostly around the side navigation and clicking on specific tag links

**Comment by pereiragislene** [comment]
I run the functional tests around 30 times and in 2 situations I got the following failure.
I was not able to reproduce the failure manually nor could see the failure happen on the tests anymore.

```
Feature: Checkboxes # test/functional/features/checkboxes_and_mailboxes.feature:17
  As a user of Pixelated
  I want to use checkboxes to manage my emails
  So I can manage more than one email at once
  Scenario: User has a list of emails in each mailboxes that needs to be managed  # test/functional/features/checkboxes_and_mailboxes.feature:22
    Given I have a mail in my inbox                                               # test/functional/features/steps/data_setup.py:21 0.010s
    When I select the tag 'inbox'                                                 # test/functional/features/steps/tag_list.py:37 1.200s
    And I mark the first unread email as read                                     # test/functional/features/steps/mail_list.py:84 10.227s
Traceback (most recent call last):
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/vagrant/service/test/functional/features/steps/mail_list.py", line 91, in impl
          email.find_element_by_tag_name('input').click()
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 184, in find_element_by_tag_name
          return self.find_element(by=By.TAG_NAME, value=name)
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 392, in find_element
          {"using": by, "value": value})['value']
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 385, in _execute
          return self._parent.execute(command, params)
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
          self.error_handler.check_response(response)
        File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
          raise exception_class(message, screen, stacktrace)
      StaleElementReferenceException: Message: {"errorMessage":"Element does not exist in cache","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Conn
ection":"close","Content-Length":"120","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:54197","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST"
,"post":"{\"using\": \"tag name\", \"sessionId\": \"0c9aa030-5aec-11e5-962d-33b6775c07da\", \"id\": \":wdc:1442240557923\", \"value\": \"input\"}","url":"/element","urlParsed":{"anc
hor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","s
ource":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/0c9aa030-5aec-11e5-962d-33b6775c07da/element/%3Awdc%3A1442240557923/element"}}
      Screenshot: available via screen

And I delete the email                                                        # None
    When I select the tag 'trash'                                                 # None
    Then the deleted mail is there                                                # None
    When I check all emails                                                       # None
    And I delete them permanently                                                 # None
    Then I should not see any email
```
