### ISSUE TITLE
[wazokazi] Can't send email to user on same provider / SSL3_GET_SERVER_CERTIFICATE

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#461]
Observed on wazokazi on 2015-09-17 07:44:24 +0000. Steps to reproduce:

1) Open pixelated on wazokazi
2) Compose new mail. Recipient is yourself.
3) Send

Expected: I receive the mail as unread in my mailbox
Actual: I don't receive a mail

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/incoming/service.py", line 618, in _extract_keys
    dh = self._extract_openpgp_header(header, fromAddress)
  File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/incoming/service.py", line 661, in _extract_openpgp_header
    d = self._keymanager.fetch_key(address, url, OpenPGPKey)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/__init__.py", line 782, in fetch_key
    res = self._get(uri)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/__init__.py", line 166, in _get
    res = self._fetcher.get(uri, data=data, verify=self._ca_cert_path)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

2015-09-17 07:44:24 [twisted] CRITICAL Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/incoming/service.py", line 618, in _extract_keys
    dh = self._extract_openpgp_header(header, fromAddress)
  File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/incoming/service.py", line 661, in _extract_openpgp_header
    d = self._keymanager.fetch_key(address, url, OpenPGPKey)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/__init__.py", line 782, in fetch_key
    res = self._get(uri)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/__init__.py", line 166, in _get
    res = self._fetcher.get(uri, data=data, verify=self._ca_cert_path)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

2015-09-17 07:44:24 [twisted] INFO there are 1 mails
```

**Comment by fbernitt** [comment]
Problem is that the KeyManager fails to validate connection with the server when trying to load GPG key that is part of the mail header:

```
OpenPGP: id=8659A94CEE0B32A2; url="https://wazokazi.is/key/folker2";
        preference="signencrypt"
```

The ca.crt file provided by wazokazi.is (https://wazokazi.is/ca.crt) is able to verify the request, though.

**Comment by fbernitt** [comment]
KeyManager gets whatever 
```
LeapCertificate(provider).provider_api_cert
```
returns, very likely a path to some ~/.leap/providers/wazokazi.is/keys/client/api.pem. This file contains a self-signed LEAP root CA, that is used for api and other services. Problem now is, that wazokazi.is on port 443 uses a commercial certificate (and not one signed by the CA in api.pem). For that reason, when the KeyManager tries to retrieve the key from https://wazokazi.is/key/folker2 it can't verify the presented cert with what is in api.pem.

**Comment by fbernitt** [comment]
You can reproduce this problem with these tests:
```bash
SSL_CERT_FILE=/dev/null SSL_CERT_DIR=/dev/null openssl s_client -CAfile ~/.leap/providers/wazokazi.is/keys/client/api.pem -connect wazokazi.is:443
```
or
```python
import requests
from os.path import expanduser

ca_path = expanduser('~/.leap/providers/wazokazi.is/keys/client/api.pem' )

requests.get('https://wazokazi.is/key/folker2', verify=ca_path)
```

**Comment by fbernitt** [comment]
Waiting for PR: https://github.com/leapcode/keymanager/pull/82

**Comment by fbernitt** [comment]
Created second PR as a fixup: https://github.com/leapcode/keymanager/pull/87
