### ISSUE TITLE
Error problems talking to server

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#467]
the problem is: 
Sending email 1st time I got "problems talking to server". 
After retrying, it worked.

**Comment by cz8s** [comment]
I also got this error. Here is the trace:
```
2015-09-25 14:14:10 [leap.common.check] ERROR Bug: Need to create doc before deleting
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/bin/pixelated-user-agent", line 9, in <module>
2015-09-25 14:14:10 [leap.common.check] ERROR     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/application.py", line 100, in initialize
2015-09-25 14:14:10 [leap.common.check] ERROR     reactor.run()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
2015-09-25 14:14:10 [leap.common.check] ERROR     self.mainLoop()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
2015-09-25 14:14:10 [leap.common.check] ERROR     self.runUntilCurrent()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
2015-09-25 14:14:10 [leap.common.check] ERROR     f(*a, **kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
2015-09-25 14:14:10 [leap.common.check] ERROR     self._startRunCallbacks(result)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     self._runCallbacks()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     current.result = callback(current.result, *args, **kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 859, in _cbDeferred
2015-09-25 14:14:10 [leap.common.check] ERROR     self.callback(self.resultList)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
2015-09-25 14:14:10 [leap.common.check] ERROR     self._startRunCallbacks(result)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     self._runCallbacks()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     current.result = callback(current.result, *args, **kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
2015-09-25 14:14:10 [leap.common.check] ERROR     _inlineCallbacks(r, g, deferred)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     result = g.send(result)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 290, in delete_mail
2015-09-25 14:14:10 [leap.common.check] ERROR     yield message.get_wrapper().delete(self.soledad)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 612, in delete
2015-09-25 14:14:10 [leap.common.check] ERROR     d.append(self.fdoc.delete(store))
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 202, in delete
2015-09-25 14:14:10 [leap.common.check] ERROR     return self._lock.run(self._delete, store)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1318, in run
2015-09-25 14:14:10 [leap.common.check] ERROR     d.addCallback(execute)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
2015-09-25 14:14:10 [leap.common.check] ERROR     callbackKeywords=kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     self._runCallbacks()
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-09-25 14:14:10 [leap.common.check] ERROR     current.result = callback(current.result, *args, **kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1313, in execute
2015-09-25 14:14:10 [leap.common.check] ERROR     d = maybeDeferred(f, *args, **kwargs)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
2015-09-25 14:14:10 [leap.common.check] ERROR     result = f(*args, **kw)
2015-09-25 14:14:10 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 206, in _delete
2015-09-25 14:14:10 [leap.common.check] ERROR     "Need to create doc before deleting")
Unhandled error in Deferred:
2015-09-25 14:14:10 [twisted] CRITICAL Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1313, in execute
    d = maybeDeferred(f, *args, **kwargs)
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 206, in _delete
    "Need to create doc before deleting")
  File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
    assert condition, message
exceptions.AssertionError: Need to create doc before deleting
```

**Comment by cz8s** [comment]
problem is, that the mail is sent, but doesn't show up in the sent folder.
This makes the problem even worse, because people will get the error and send the mail
twice or think they didn't send the mail at all.

**Comment by bwagnerr** [comment]
related to #470, possibly fixed
