### ISSUE TITLE
Simple repair tool for broken accounts

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#468]
A simple repair tool as part of the maintenance script that repairs accounts with broken key entries.

- Should remove all public key entries (key doc and active key doc) for which no private key doc exists
- Shoiuld keep the entries for all keys with private key docs

**Comment by fbernitt** [comment]
Added repair as a new option to the pixelated-maintenance script, just call:
```
pixelated-maintenance repair
```
to fix an account with key id problems.

**Comment by cz8s** [comment]
Tried to fix my account on wazokazi, didn't work. I used the user-agent package inside the lates docker build:
```
root@b4db50c831b9:/# pixelated-maintenance repair
Traceback (most recent call last):
  File "/usr/bin/pixelated-maintenance", line 9, in <module>
    load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-maintenance')()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/maintenance.py", line 21, in <module>
    from pixelated.adapter.mailstore.maintenance import SoledadMaintenance
ImportError: No module named maintenance
```

**Comment by cz8s** [comment]
tried to repair cz8s@wazokazi.is. repair deleted some docs, but after repair I get
``` ERROR exceptions.AssertionError: Wrong address in key 761401CFFB4A48CF. Expected cz8s@wazokazi.is, found [u'gliberat@wazokazi.is'].```

**Comment by kaeff** [comment]
I tried to repair user kaeff4@wazokazi.is. I executed the script locally and got the following output. Still can't login afterwards.

```
2015-09-29 23:22:16 [some logger] WARNING Before sync
2015-09-29 23:22:26 [some logger] WARNING after sync
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-08f7a0b059ff434980c9e2493f85af5a for key DFDDB7A12C23AF80 of <kaeff4@wazokazi.is>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-15fc58296f9a44d7843ef88c0bf1d202 for key A34DDA548A86B149 of <[u'folker16@wazokazi.is']>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-219bbf73d3af4cddbcef3fa04d0bdf3f for key 120EAD687EEBFC35 of <galbo@thoughtworks.com>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-2c7c27c80f984c148112d2e540b6875f for key DFDDB7A12C23AF80 of <[u'galbo@wazokazi.is']>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-58286c7ab1cb488ab2e5b5f3d4335074 for key 3CD3B5D9DA52029D of <[u'kfleerko@thoughtworks.com']>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-64e78491947a41a58e10b449154757b9 for key 3CD3B5D9DA52029D of <kfleerko@thoughtworks.com>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-80b44ae9e7c94201a919db84f0257ee0 for key DFDDB7A12C23AF80 of <galbo@wazokazi.is>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-81ba6d56ab6f43c5b0f6beb22236fcab for key A34DDA548A86B149 of <folker16@wazokazi.is>
2015-09-29 23:22:26 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-9fb55d6dbcb0426aa8f49690f6a05b01 for key 120EAD687EEBFC35 of <[u'galbo@thoughtworks.com']>
[Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get'
/Users/kfleerko/.virtualenvs/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
/Users/kfleerko/.virtualenvs/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:70:repair
/Users/kfleerko/.virtualenvs/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/Users/kfleerko/.virtualenvs/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:74:_repair_missing_active_docs
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:85:_missing_active_docs
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:99:_active_docs_for_key_id
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:40:_is_active_key_doc
/Users/kfleerko/code/gh/pixelated/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:32:_is_key_doc
]
```

**Comment by shyba** [comment]
I handed it to @kaeff since he is aware of this error.
Let's catch up tomorrow to see what can be done?

**Comment by kaeff** [comment]
I tried repairing on multiple accounts, but despite the exceptions occuring, all accounts could be repaired successfully.

Since we've spend quite some time now and `repair` seems to fix accounts that have the `Wrong Adress in key` problem quite reliably, I'm in favor of launching this.
