### ISSUE TITLE
user-agent are trying delete an deleted documents

### ISSUE THREAD

**Issue by jeffhsta** [pixelated/pixelated-user-agent#470]
The problem is the user agent make a HTTP request to save the draft more then once at the same time.
The user agent logic on save draft is create a new one and delete the old one, so if I do this at the same time it will create a new draft and try delete the old one that will be delete for the thread that execute fist.

The same happen when user agent are trying send an email and save the draft at the same time.

To reproduce this error:
When start compose an email and click too many times on "Save Draft" button
Then the below stack trace will be shown on the logs

Traceback (most recent call last):
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
callbackKeywords=kw)
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
self._runCallbacks()
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1313, in execute
d = maybeDeferred(f, *args, **kwargs)
--- <exception caught here> ---
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
result = f(*args, **kw)
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 206, in _delete
"Need to create doc before deleting")
File "/home/jstachel/code/pixelated-project/pixelated-user-agent/.venv/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
assert condition, message
exceptions.AssertionError: Need to create doc before deleting

**Comment by jeffhsta** [comment]
I fix the bug that save a lot duplication drafts if the "Save Draft" button is pressed too many times, but still have the bug that if the buttons "Send" and "Save Draft" are pressed almost the same time, the mail will be sent but the draft will be not deleted as should be

**Comment by jeffhsta** [comment]
Could not reproduce the error when trying click "Send" and then "Save Draft" or vice versa at same time.
Maybe it was solved with commit 6df9e2c

**Comment by neissi** [comment]
I created a new account and reproduce the steps and then 11 drafts was created (the same mail)

<img width="1280" alt="screen shot 2015-09-29 at 5 55 07 pm" src="https://cloud.githubusercontent.com/assets/4038257/10177892/02006fd6-66d3-11e5-8d78-cf4e39bb2965.png">

**Comment by neissi** [comment]
Was created a new issue #481 do deal with this bug.
