### ISSUE TITLE
found more than one key for address

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#471]
Mails from cwagner can not be received and the padlock stays orange if I want to send to that address.
```
2015-09-25 19:32:52 [twisted] CRITICAL Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 540, in get_key_from_active_doc
    'Found more than one key for address %s!' % (address,))
  File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
    assert condition, message
exceptions.AssertionError: Found more than one key for address cwagner@wazokazi.is!
```

**Comment by cz8s** [comment]
this is a dup of #479
