### ISSUE TITLE
Cannot start pixelated using the 'dev.pixelated-project.org'  provider.

### ISSUE THREAD

**Issue by SamuelToh** [pixelated/pixelated-user-agent#472]
Hi all,

I was trying to start my pixelated application using the dev provider but it is refusing to let me do so.

Any expert out there can help me with this?

It is saying:
2015-09-26 08:11:23 [leap.soledad.client.crypto] WARNING Wrong MAC while decrypting doc... 
leap.soledad.common.crypto.WrongMacError: Could not authenticate document's contents.

Then an unhandled exception was thrown. See details below.

Here is what i am trying to do:
-----------------------------------------------
 (user-agent-venv)vagrant@leap-wheezy:/vagrant/service$ pixelated-user-agent --host 0.0.0.0 -lc /vagrant/service/pixelated/certificates/dev.pixelated-project.org.ca.crt

015-09-26 08:10:45 [twisted] INFO PixelatedSite starting on 3333
2015-09-26 08:10:45 [twisted] INFO Starting factory <pixelated.config.site.PixelatedSite instance at 0x4af0758>
Which provider do you want to connect to:
dev.pixelated-project.org
What's your username registered on the provider:
stoh
Type your password: 
<my_password>

---------------------------------------
This is what it reports:

2015-09-26 08:10:55 [requests.packages.urllib3.connectionpool] INFO Starting new HTTPS connection (1): dev.pixelated-project.org

2015-09-26 08:11:09 [requests.packages.urllib3.connectionpool] INFO Starting new HTTPS connection (1): api.dev.pixelated-project.org
2015-09-26 08:11:10 [leap.soledad.client.api] INFO Creating directory: /home/vagrant/.config/leap/soledad.
2015-09-26 08:11:10 [leap.soledad.client.secrets] INFO Checking if there's a secret in local storage...
2015-09-26 08:11:10 [leap.soledad.client.secrets] INFO Could not find a secret in local storage.
2015-09-26 08:11:10 [leap.soledad.client.secrets] INFO Trying to fetch cryptographic secrets from shared recovery database...
2015-09-26 08:11:13 [leap.soledad.client.secrets] INFO Found cryptographic secrets in shared recovery database.
2015-09-26 08:11:14 [requests.packages.urllib3.connectionpool] INFO Starting new HTTPS connection (1): api.dev.pixelated-project.org
2015-09-26 08:11:16 [twisted] INFO Starting factory <leap.common.http._HTTP11ClientFactory instance at 0x4b07c20>
2015-09-26 08:11:23 [twisted] INFO Starting factory <leap.common.http._HTTP11ClientFactory instance at 0x4d8e518>
2015-09-26 08:11:23 [twisted] INFO Starting factory <leap.common.http._HTTP11ClientFactory instance at 0x4d8ed88>
2015-09-26 08:11:23 [twisted] INFO Starting factory <leap.common.http._HTTP11ClientFactory instance at 0x4d93758>

*****************
2015-09-26 08:11:23 [leap.soledad.client.crypto] WARNING Wrong MAC while decrypting doc... <--- Could be of interest
Unhandled Error
********************

Stack trace:
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 799, in _decrypt_and_recurse
    self._collect_async_decryption_results()
  File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 776, in _collect_async_decryption_results
    self._decrypt_doc_cb(res.get())  # might raise an exception!
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
leap.soledad.common.crypto.WrongMacError: Could not authenticate document's contents.

2015-09-26 08:11:23 [twisted] CRITICAL Unhandled Error
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 799, in _decrypt_and_recurse
    self._collect_async_decryption_results()
  File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 776, in _collect_async_decryption_results
    self._decrypt_doc_cb(res.get())  # might raise an exception!
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
leap.soledad.common.crypto.WrongMacError: Could not authenticate document's contents.

2015-09-26 08:12:02 [leap.soledad.client.api] ERROR Soledad exception when syncing!
*--- Failure #8 (pickled) ---
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:393: callback(...)
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:501: _startRunCallbacks(...)
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:588: _runCallbacks(...)
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128: _inlineCallbacks(...)
/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py:799: _decrypt_and_recurse(...)
/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py:776: _collect_async_decryption_results(...)
/usr/lib/python2.7/multiprocessing/pool.py:554: get(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
leap.soledad.common.crypto.WrongMacError: Could not authenticate document's contents.
*--- End of Failure #8 ---

2015-09-26 08:12:02 [twisted] ERROR Traceback (most recent call last):
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
2015-09-26 08:12:02 [twisted] ERROR     self._startRunCallbacks(result)
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
2015-09-26 08:12:02 [twisted] ERROR     self._runCallbacks()
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-09-26 08:12:02 [twisted] ERROR     current.result = callback(current.result, *args, **kw)
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
2015-09-26 08:12:02 [twisted] ERROR     _inlineCallbacks(r, g, deferred)
2015-09-26 08:12:02 [twisted] ERROR --- <exception caught here> ---
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
2015-09-26 08:12:02 [twisted] ERROR     result = g.send(result)
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 799, in _decrypt_and_recurse
2015-09-26 08:12:02 [twisted] ERROR     self._collect_async_decryption_results()
2015-09-26 08:12:02 [twisted] ERROR   File "/home/vagrant/user-agent-venv/src/leap.soledad.client/client/src/leap/soledad/client/encdecpool.py", line 776, in _collect_async_decryption_results
2015-09-26 08:12:02 [twisted] ERROR     self._decrypt_doc_cb(res.get())  # might raise an exception!
2015-09-26 08:12:02 [twisted] ERROR   File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
2015-09-26 08:12:02 [twisted] ERROR     raise self._value
2015-09-26 08:12:02 [twisted] ERROR leap.soledad.common.crypto.WrongMacError: Could not authenticate document's contents.
2015-09-26 08:12:02 [twisted] INFO Stopping factory <leap.common.http._HTTP11ClientFactory instance at 0x4d8e518>
2015-09-26 08:12:02 [twisted] INFO (TCP Port 3333 Closed)

**Comment by shyba** [comment]
Hello!
Is that an old account?
This error usually appears when you try to use an old account (created with Soledad 0.6) on current Pixelated version. We are using Soledad latest code now and the document signature scheme changed, leaving old documents unusable with current version. This is why you are getting a "WrongMacError".

Feel free to [create another developer account](https://dev.pixelated-project.org/signup).

Please, also consider deleting contents on folder `~/.leap` to ensure that old data doesn't conflict and ping back if the problem persists.

**Comment by SamuelToh** [comment]
Hi all,

sorry for the late reply as I was trying to get my fork'ed version of pixelated to build before I could verify that it was fixed.

I'm not sure what is going on with my leap-wheezy vagrant box but it was failing with the following error while doing the ./go setup step.

  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)


as advised by the error message, installing libpng-dev (sudo apt-get install libpng-dev) has made the error gone away. 

Now that my leap-wheezy box is working again, I confirm that the issue has been fixed 

Thanks all!
