### ISSUE TITLE
Encoding error on received mail

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#473]
When receiving a new mail, I see it on the list but can't open it (I get error when opening mail). On the logs I have the following error:

```
2015-09-28 13:40:07 [twisted] CRITICAL Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 201, in get_mail
    leap_mail = yield self._leap_message_to_leap_mail(mail_id, message, include_body)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 331, in _leap_message_to_leap_mail
    body = yield self._raw_message_body(message)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 347, in _raw_message_body
    defer.returnValue(parser.parsed_content())
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/body_parser.py", line 37, in parsed_content
    text = self._serialize_for_parser(charset)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/body_parser.py", line 58, in _serialize_for_parser
    text += self._content.encode(charset)
exceptions.UnicodeEncodeError: 'latin-1' codec can't encode character u'\ufffd' in position 155: ordinal not in range(256)
```

**Comment by giovaneliberato** [comment]
@bwagnerr Do you remember what was on the mail? I try using characters like ü but the user agente could open it.

The "\ufffd" representas a [replacement character](http://www.fileformat.info/info/unicode/char/0fffd/index.htm), which is used when no character was found on the encoding.

Here's a screenshot of the examples I tried

<img width="1252" alt="screen shot 2015-10-02 at 4 24 43 pm" src="https://cloud.githubusercontent.com/assets/2964631/10255639/221e689e-6922-11e5-993e-b4db2e0c9323.png">

**Comment by fbernitt** [comment]
This fix actually fixes a problem with encodings. There has been an implicit conversion of the encoded result back from str to unicode because the text variable had been unicode. 

The problem described in this issue is not fixed, though. It seems to be a problem within leap_mail that replaces unknown chars with the unicode unknown char (fffd).

Working on a bug report for leap_mail.

**Comment by cz8s** [comment]
we still haven't found the bug in leap-mail. will continue next week ....

**Comment by cz8s** [comment]
this error only occurs with iso encoded messages that use 8bit and have umlauts.
mails from e.g. gmail are not affected.
only client creating this sort of mail is unencrypted mails by mutt with umlauts in the body.
Therefore I remove the wazokazi label

**Comment by jeffhsta** [comment]
@cz8s please check it out again, lets see if what I did fixed the problem

**Comment by fbernitt** [comment]
I think ignoring the problem is good enough for now, just added a logger for it. The root problem still exisits though and we are not able to parse valid mails for yet unkown reasons.
