### ISSUE TITLE
Can't receive new mails: There is 2 keys for id <ID>

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#479]
```
2015-09-29 19:14:13 [leap.common.check] ERROR Bug: There is 2 keys for id 1CDED7DF3F8C43C5!
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/bin/pixelated-user-agent", line 9, in <module>
2015-09-29 19:14:13 [leap.common.check] ERROR     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/application.py", line 100, in initialize
2015-09-29 19:14:13 [leap.common.check] ERROR     reactor.run()
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
2015-09-29 19:14:13 [leap.common.check] ERROR     self.mainLoop()
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
2015-09-29 19:14:13 [leap.common.check] ERROR     self.runUntilCurrent()
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
2015-09-29 19:14:13 [leap.common.check] ERROR     f(*a, **kw)
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
2015-09-29 19:14:13 [leap.common.check] ERROR     self._startRunCallbacks(result)
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
2015-09-29 19:14:13 [leap.common.check] ERROR     self._runCallbacks()
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-09-29 19:14:13 [leap.common.check] ERROR     current.result = callback(current.result, *args, **kw)
2015-09-29 19:14:13 [leap.common.check] ERROR   File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 542, in get_doc
2015-09-29 19:14:13 [leap.common.check] ERROR     'There is %d keys for id %s!' % (len(doclist), key_id))
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 542, in get_doc
    'There is %d keys for id %s!' % (len(doclist), key_id))
  File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
    assert condition, message
exceptions.AssertionError: There is 2 keys for id 1CDED7DF3F8C43C5!
```

**Comment by pereiragislene** [comment]
@bwagnerr: do you remember the steps to reproduce this? Is this account still broken?

**Comment by bwagnerr** [comment]
@pereiragislene currently cwagner has that problem in wazokazi, so if you try to send a mail to that account you'll get the error

**Comment by kaeff** [comment]
`pixelated-maintenance repair` should fix this problem. Or is this card about eliminating the root cause?

**Comment by shyba** [comment]
For reference, maybe related: #471

**Comment by bwagnerr** [comment]
@kaeff I think repair won't fix it because both keys got uploaded to keymanager, and everyone that ever received any mail from that account has that error.
I am not sure if the accounts are broken or if that's the only mail not being processed, in the second case I think we can ignore it by now

**Comment by bwagnerr** [comment]
So we discussed this today and I'll close the issue because we are not seeing the problem anymore. We should reopen it if this comes up again
