### ISSUE TITLE
pixelated-register fails on try

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#480]
when the pipeline runs pixelated-register on try to create alice,bob and eve, it fails with this error:
```
19:22:18.572 Unhandled error in Deferred:
19:22:18.572 2015-09-30 19:22:19 [twisted] CRITICAL Unhandled error in Deferred:
19:22:18.574 
19:22:18.575 
19:22:18.575 Traceback (most recent call last):
19:22:18.575   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
19:22:18.575     self._startRunCallbacks(fail)
19:22:18.575   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
19:22:18.576     self._runCallbacks()
19:22:18.576   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
19:22:18.576     current.result = callback(current.result, *args, **kw)
19:22:18.576   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
19:22:18.577     _inlineCallbacks(r, g, deferred)
19:22:18.577 --- <exception caught here> ---
19:22:18.577   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
19:22:18.577     result = result.throwExceptionIntoGenerator(g)
19:22:18.578   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
19:22:18.578     return g.throw(self.type, self.value, self.tb)
19:22:18.578   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/maintenance.py", line 149, in load_mails
19:22:18.578     yield add_mail_folder(store, maildir, 'INBOX', deferreds)
19:22:18.578   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
19:22:18.579     result = result.throwExceptionIntoGenerator(g)
19:22:18.579   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
19:22:18.579     return g.throw(self.type, self.value, self.tb)
19:22:18.579   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/maintenance.py", line 124, in add_mail_folder
19:22:18.580     yield store.add_mailbox(folder_name)
19:22:18.580   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
19:22:18.580     result = result.throwExceptionIntoGenerator(g)
19:22:18.580   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
19:22:18.581     return g.throw(self.type, self.value, self.tb)
19:22:18.581   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 257, in add_mailbox
19:22:18.581     mailbox = yield self._get_or_create_mailbox(mailbox_name)
19:22:18.581   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
19:22:18.581     result = result.throwExceptionIntoGenerator(g)
19:22:18.582   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
19:22:18.582     return g.throw(self.type, self.value, self.tb)
19:22:18.582   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/mailstore/leap_mailstore.py", line 357, in _get_or_create_mailbox
19:22:18.582     mbx = yield SoledadMailAdaptor().get_or_create_mbox(self.soledad, mailbox_name_upper)
19:22:18.583   File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
19:22:18.583     current.result = callback(current.result, *args, **kw)
19:22:18.583   File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/adaptors/soledad.py", line 251, in try_to_get_doc_from_index
19:22:18.583     idx_def = dict(indexes)[index]
19:22:18.584 exceptions.KeyError: 'by-type-and-mbox'
19:22:18.584 2015-09-30 19:22:19 [twisted] CRITICAL 
```

But after that, the users are created and everything works. Only the script hangs and doesn't return
impact: the pipeline never gets green

**Comment by kaeff** [comment]
The pipeline is green again, can be closed?

**Comment by cz8s** [comment]
this is a dup of #469
