### ISSUE TITLE
"Found more than one key" error

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#510]
hi, i tried today connecting latest useragent running locally to my account on wazokazi.

it failed complaining about finding more than one key from the same email adr:

```
(.virtualenv)--- pixelated-user-agent/config ‹master* M› » pixelated-user-agent --config /home/varac/thoughtworks/git/pixelated-user-agent/config/wazokazi.is.config


The key len is: 90
2015-11-04 14:53:12 [leap.common.check] ERROR Bug: Found more than one key for address nospam@plea.se!
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/bin/pixelated-user-agent", line 9, in <module>
2015-11-04 14:53:12 [leap.common.check] ERROR     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/application.py", line 105, in initialize
2015-11-04 14:53:12 [leap.common.check] ERROR     reactor.run()
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
2015-11-04 14:53:12 [leap.common.check] ERROR     self.mainLoop()
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
2015-11-04 14:53:12 [leap.common.check] ERROR     self.runUntilCurrent()
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
2015-11-04 14:53:12 [leap.common.check] ERROR     f(*a, **kw)
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
2015-11-04 14:53:12 [leap.common.check] ERROR     self._startRunCallbacks(result)
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
2015-11-04 14:53:12 [leap.common.check] ERROR     self._runCallbacks()
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2015-11-04 14:53:12 [leap.common.check] ERROR     current.result = callback(current.result, *args, **kw)
2015-11-04 14:53:12 [leap.common.check] ERROR   File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 532, in get_key_from_active_doc
2015-11-04 14:53:12 [leap.common.check] ERROR     'Found more than one key for address %s!' % (address,))
Unhandled Error
Traceback (most recent call last):
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 532, in get_key_from_active_doc
    'Found more than one key for address %s!' % (address,))
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
    assert condition, message
exceptions.AssertionError: Found more than one key for address nospam@plea.se!

2015-11-04 14:53:12 [twisted] CRITICAL Unhandled Error
Traceback (most recent call last):
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(*a, **kw)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/src/leap.keymanager/src/leap/keymanager/openpgp.py", line 532, in get_key_from_active_doc
    'Found more than one key for address %s!' % (address,))
  File "/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/src/leap.common/src/leap/common/check.py", line 48, in leap_assert
    assert condition, message
exceptions.AssertionError: Found more than one key for address nospam@plea.se!

...
```

i tried to repair:
```
(.virtualenv)--- pixelated-user-agent/config ‹master* M› » pixelated-maintenance --config /home/varac/thoughtworks/git/pixelated-user-agent/config/wazokazi.is.config repair              

2015-11-04 15:24:54 [some logger] WARNING Before sync
2015-11-04 15:24:55 [some logger] WARNING after sync
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-00cb7893d8884f46b5d02a1083eaf06e for key 15B74D1CC379314A of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-13a6bb2f33a24027b32506425701ae8d for key 5465E77E7876ED04 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-18f6954ab9cd4803a55a1d4df782199b for key 6D6E628A4FCB23BB of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-1cc927722689405386cc28ae95a003b0 for key F47CA30F3D1BBF29 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-1cef6482a53b4d7c9e77df0c5b509b7d for key 23E019842C7FD63F of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-2a40eaec4a634b5b81159e3cb6957c1c for key 5465E77E7876ED04 of <[u'nospam@plea.se', u'nospam@plea.se', u'nospam@plea.se', u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-30bb458767e54e129da7df90843e6baa for key 549DAD0B63C89B9C of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-31fd3d92c9fd444b9164518af712ee27 for key CF135AE47109A1C1 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-3cfcc7d9161a410e91bcba94ce746fa2 for key 79DC00CCA81CCBC1 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-4ec245a1ac27419bb16e8d1ef670ad6f for key 6D6E628A4FCB23BB of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-52bc829dee52465190c23df421c2fdbc for key 821116EBF08FD031 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-5dcee58391e14337ab99d936f896c041 for key 64E288488E60308F of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-5dfebaa260ef4212b0e361cb4257a4fe for key C32969E84FC05091 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-6e309c6ea5db454f9ec836bb0d1eb7df for key 15B74D1CC379314A of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-77a27e2bc2dc4e50ab52b9dbcdfcc16c for key F47CA30F3D1BBF29 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-9134152d47a148c7b2ecfab992ed7242 for key 79DC00CCA81CCBC1 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-a01f0d6f684c496fa0683092f1e8c557 for key 821116EBF08FD031 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-a1b4291efd5842aebfdfb500ef4d9dd2 for key C32969E84FC05091 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-a31adb5e34ae488b9ddedc73a3abedae for key CF135AE47109A1C1 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-a884c08931654b8ea3cff0abfa28b282 for key 15B74D1CC379314A of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-b433a2392c9648e1bd489ec0f26a8e1f for key 821116EBF08FD031 of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-ba5fa25d4d2e428f9227c9b887649ac6 for key 23E019842C7FD63F of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-c8d8af77dea04af68318c3fb5bb6deb2 for key 821116EBF08FD031 of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-cc6006bcf4384bee905bad6c0aab51a2 for key 15B74D1CC379314A of <[u'nospam@plea.se']>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-d29e57d2ae2148319a62fda7dbfb6d47 for key 549DAD0B63C89B9C of <nospam@plea.se>
2015-11-04 15:24:55 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-d3082863cb1e4bafa1f0ad8827b35296 for key 64E288488E60308F of <nospam@plea.se>
[Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get'
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:70:repair
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:74:_repair_missing_active_docs
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:85:_missing_active_docs
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:99:_active_docs_for_key_id
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:40:_is_active_key_doc
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:32:_is_key_doc
]

```

i needed to run the repair script twice again until it finished without error:
```
(.virtualenv)--- pixelated-user-agent/config ‹master* M› » pixelated-maintenance --config /home/varac/thoughtworks/git/pixelated-user-agent/config/wazokazi.is.config repair              1 ↵
2015-11-04 15:49:14 [some logger] WARNING Before sync
2015-11-04 15:49:14 [some logger] WARNING after sync
2015-11-04 15:49:14 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-b33d0f9e27374058b0c9bc5c93fe5b37 for key 821116EBF08FD031 of <[u'nospam@plea.se']>
2015-11-04 15:49:14 [pixelated.adapter.mailstore.maintenance] WARNING Deleting doc D-fab4e371d6224153a3bbc4714a9ced20 for key 821116EBF08FD031 of <nospam@plea.se>
[Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'get'
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:70:repair
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:74:_repair_missing_active_docs
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:85:_missing_active_docs
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:99:_active_docs_for_key_id
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:40:_is_active_key_doc
/home/varac/thoughtworks/git/pixelated-user-agent/service/pixelated/adapter/mailstore/maintenance/__init__.py:32:_is_key_doc

(.virtualenv)--- pixelated-user-agent/config ‹master* M› » pixelated-maintenance --config /home/varac/thoughtworks/git/pixelated-user-agent/config/wazokazi.is.config repair
2015-11-04 15:49:30 [some logger] WARNING Before sync
2015-11-04 15:49:34 [some logger] WARNING after sync
2015-11-04 15:49:34 [some logger] WARNING Before sync
2015-11-04 15:49:34 [some logger] WARNING after sync

```

after repairing, the useragent works again.

i searched for the first timestamp in my userdb, and it was first accessed on: `Mon Sep 28 16:14:12 CEST 2015`

@fbernitt said that the commit fixing the above bug was from Sept 24th, so we're not sure if my db was created from an instance that his the fix already deployed

so i don't know if we should care for the duplicate key error, but needing to run the repair script 3 times should be fixed.

**Comment by kaeff** [comment]
A while back I spent some time figuring out the problem with double-runs of repair: https://github.com/pixelated/pixelated-user-agent/issues/468

Since it was hard to reproduce (duplicated key bug was fixed) and accounts could be repaired eventually, we launched the original issue.

**Comment by giovaneliberato** [comment]
I QAd that by looking trought all the logs. No occurrences of this error found!
