### ISSUE TITLE
Error when using expired key

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#516]
What
---
One of our users had an external address with a key that would expire at November, 1st. He tried sending a mail to that address today, but got the error below. He extended the expiration date of his key before trying to send this new email, so Pixelated should have refreshed/fetched the updated key.

Definition of done
---
To be defined

Stacktrace

2015-11-05 13:17:15 [twisted] CRITICAL something failed
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_service.py", line 92, in send_mail
    yield self.mail_sender.sendmail(mail)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_sender.py", line 57, in sendmail
    raise MailSenderException('Failed to send mail to all recipients', error_map)
pixelated.adapter.services.mail_sender.MailSenderException: ('Failed to send mail to all recipients', {u'<email>': None, u'<email>': <twisted.python.failure.Failure leap.keymanager.errors.EncryptError: >})

2015-11-05 13:18:00 [leap.keymanager.openpgp] ERROR Failed to decrypt: Failed to encrypt/decrypt: [GNUPG:] GOOD_PASSPHRASE
[GNUPG:] KEYEXPIRED 1446381172
[GNUPG:] SIGEXPIRED deprecated-use-keyexpired-instead
gpg: EA1CD12E48DE2BF7DFE5E46A98EC414B11B44054: skipped: unusable public key
[GNUPG:] INV_RECP 0 EA1CD12E48DE2BF7DFE5E46A98EC414B11B44054
gpg: [stdin]: sign+encrypt failed: unusable public key
.
Unhandled Error
Traceback (most recent call last):
Failure: leap.keymanager.errors.EncryptError:

**Comment by fbernitt** [comment]
Seems to me like a keymanager issue?

**Comment by bwagnerr** [comment]
fbernitt: Indeed, should we open a issue for this on leap itself?

**Comment by bwagnerr** [comment]
Hey, created an issue on leap for this https://leap.se/code/issues/7612
