### ISSUE TITLE
Provisioning fails to update pip

### ISSUE THREAD

**Issue by juniorz** [pixelated/pixelated-user-agent#518]
It seems to be a dependency between setuptools and pip. Upgrading setuptools before pip on the same command breaks with the following error:

```
+ pip install --upgrade setuptools pip
Downloading/unpacking distribute from https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a
  Downloading distribute-0.7.3.zip (145Kb): 145Kb downloaded
  Running setup.py egg_info for package distribute

Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
  Downloading pip-7.1.2.tar.gz (1.0Mb): 1.0Mb downloaded
  Running setup.py egg_info for package pip

    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Downloading/unpacking setuptools>=0.7 (from distribute)
  Downloading setuptools-18.5.tar.gz (626Kb): 626Kb downloaded
  Running setup.py egg_info for package setuptools

Installing collected packages: distribute, pip, setuptools
  Found existing installation: distribute 0.6.24
    Uninstalling distribute:
      Successfully uninstalled distribute
  Running setup.py install for distribute

  Found existing installation: pip 1.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    Complete output from command /vagrant/service/.virtualenv/bin/python -c "import setuptools;__file__='/vagrant/service/.virtualenv/build/pip/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-rze2RJ-record/install-record.txt --install-headers /vagrant/service/.virtualenv/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError: No module named setuptools

----------------------------------------
  Rolling back uninstall of pip
Exception:
Traceback (most recent call last):
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 250, in run
    requirement_set.install(install_options, global_options)
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1137, in install
    requirement.rollback_uninstall()
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 491, in rollback_uninstall
    self.uninstalled.rollback()
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1450, in rollback
    pth.rollback()
AttributeError: 'str' object has no attribute 'rollback'

Storing complete log in /home/vagrant/.pip/pip.log
```

Breaking into two separate upgrades OR changing the order (ugh) has fixed the issue.

**Comment by cz8s** [comment]
this was auto-closed by github, but we still need to qa ...

**Comment by bwagnerr** [comment]
We triple validated this yesterday with the strike team, everything is working like a charm!
