### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#530]
## What

Encoding problems are back:

``` 
2015-11-17 09:58:13 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for 
charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 64: 
ordinal not in range(256)
```

**Comment by bwagnerr** [comment]
@re-nobre Hey, we haven't seen this anymore and haven't been able to reproduce the problem. Should we close this and reopen it when/if we find that again?

**Comment by re-nobre** [comment]
Yep @bwagnerr, it makes sense! I'm closing it.

**Comment by varac** [comment]
i got this again today watching the logs:

```
2016-05-09T12:10:32.479507+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:10:32 [pixelated.application] INFO Starting the API on port 8080
2016-05-09T12:10:32.494405+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:10:32 [pixelated.application] INFO Running the reactor

2016-05-09T12:12:48.792381+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 60: ordinal not in range(256)
2016-05-09T12:12:48.798544+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 44: ordinal not in range(256)
2016-05-09T12:12:48.802648+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 55: ordinal not in range(256)
2016-05-09T12:12:48.806034+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 31: ordinal not in range(256)
2016-05-09T12:12:48.811042+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 44: ordinal not in range(256)
2016-05-09T12:12:48.813917+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 68: ordinal not in range(256)
2016-05-09T12:12:48.816241+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 50: ordinal not in range(256)
2016-05-09T12:12:48.836697+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 47: ordinal not in range(256)
2016-05-09T12:12:48.860430+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:48 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 71: ordinal not in range(256)
2016-05-09T12:12:49.050769+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 25: ordinal not in range(256)
2016-05-09T12:12:49.070733+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 64: ordinal not in range(256)
2016-05-09T12:12:49.178333+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 49: ordinal not in range(256)
2016-05-09T12:12:49.310359+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 52: ordinal not in range(256)
2016-05-09T12:12:49.373624+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 68: ordinal not in range(256)
2016-05-09T12:12:49.494508+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:12:49 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 32: ordinal not in range(256)
2016-05-09T12:13:04.088697+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:04 [gnupg] WARNING Using untrusted key!
2016-05-09T12:13:05.106593+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:05 [gnupg] WARNING Using untrusted key!
2016-05-09T12:13:06.593474+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:06 [gnupg] WARNING Using untrusted key!
2016-05-09T12:13:07.814543+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:07 [gnupg] WARNING Using untrusted key!
2016-05-09T12:13:11.111834+02:00 pixelated pixelated-user-agent[27519]: Traceback (most recent call last):
2016-05-09T12:13:11.111863+02:00 pixelated pixelated-user-agent[27519]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 162, in index_mails
2016-05-09T12:13:11.112113+02:00 pixelated pixelated-user-agent[27519]: self._index_mail(writer, mail)
2016-05-09T12:13:11.112132+02:00 pixelated pixelated-user-agent[27519]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 123, in _index_mail
2016-05-09T12:13:11.112140+02:00 pixelated pixelated-user-agent[27519]: mdict = mail.as_dict()
2016-05-09T12:13:11.112152+02:00 pixelated pixelated-user-agent[27519]: AttributeError: 'NoneType' object has no attribute 'as_dict'
2016-05-09T12:13:11.112300+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:11 [pixelated.adapter.listeners.mailbox_indexer_listener] ERROR 'NoneType' object has no attribute 'as_dict'
2016-05-09T12:13:11.122103+02:00 pixelated pixelated-user-agent[27519]: Traceback (most recent call last):
2016-05-09T12:13:11.122154+02:00 pixelated pixelated-user-agent[27519]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 162, in index_mails
2016-05-09T12:13:11.122173+02:00 pixelated pixelated-user-agent[27519]: self._index_mail(writer, mail)
2016-05-09T12:13:11.122207+02:00 pixelated pixelated-user-agent[27519]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 123, in _index_mail
2016-05-09T12:13:11.122223+02:00 pixelated pixelated-user-agent[27519]: mdict = mail.as_dict()
2016-05-09T12:13:11.122238+02:00 pixelated pixelated-user-agent[27519]: AttributeError: 'NoneType' object has no attribute 'as_dict'
2016-05-09T12:13:11.122261+02:00 pixelated pixelated-user-agent[27519]: 2016-05-09 12:13:11 [pixelated.adapter.listeners.mailbox_indexer_listener] ERROR 'NoneType' object has no attribute 'as_dict'

```

**Comment by re-nobre** [comment]
hey, @varac!
As the last comment had 1 month, I'd like to ask you if you saw it more times or if you know how we can try to reproduce this error. 
Thks,

**Comment by re-nobre** [comment]
I talked in person with @varac and we agreed that after we implement this issue https://github.com/pixelated/puppet-pixelated/issues/35 It will be easier to understand when this encoding problem happens.
Also, we have this issue https://github.com/pixelated/project-issues/issues/173 that can be related.

So, I'm closing this issue :)
