### ISSUE TITLE
User agent isn't stopping on critical bootstrap errors

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#535]
Example:
```
pixelated-user-agent --config=invalid -lf strange
2015-11-25 14:41:12 [twisted] ERROR Traceback (most recent call last):
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/venvs/snappix/bin/pixelated-user-agent", line 9, in <module>
2015-11-25 14:41:12 [twisted] ERROR     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/repos/pixelated/pixelated-user-agent/service/pixelated/application.py", line 79, in initialize
2015-11-25 14:41:12 [twisted] ERROR     args.leap_home)
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/venvs/snappix/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
2015-11-25 14:41:12 [twisted] ERROR     return _inlineCallbacks(None, gen, Deferred())
2015-11-25 14:41:12 [twisted] ERROR --- <exception caught here> ---
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/venvs/snappix/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
2015-11-25 14:41:12 [twisted] ERROR     result = g.send(result)
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/repos/pixelated/pixelated-user-agent/service/pixelated/config/leap.py", line 31, in initialize_leap
2015-11-25 14:41:12 [twisted] ERROR     credentials_file)
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/repos/pixelated/pixelated-user-agent/service/pixelated/config/credentials.py", line 29, in read
2015-11-25 14:41:12 [twisted] ERROR     return read_from_file(credentials_file)
2015-11-25 14:41:12 [twisted] ERROR   File "/home/vshyba/repos/pixelated/pixelated-user-agent/service/pixelated/config/credentials.py", line 45, in read_from_file
2015-11-25 14:41:12 [twisted] ERROR     config_parser.get('pixelated', 'leap_server_name'), \
2015-11-25 14:41:12 [twisted] ERROR   File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
2015-11-25 14:41:12 [twisted] ERROR     raise NoSectionError(section)
2015-11-25 14:41:12 [twisted] ERROR ConfigParser.NoSectionError: No section: 'pixelated'
```

It keeps running, but this error should trigger a system exit.

Definition of done
=================
Given a bad argument or critical error during bootstrap, user agent should quit with exit code 1.

**Comment by mnandri** [comment]
To QA:
add bad argument on both single user or multi user mode,  the user-agent will not start up... the process will exit.

**Comment by cz8s** [comment]
Tried these invocations:
```
 /usr/bin/pixelated-user-agent --config=invalid -lf strange
 /usr/bin/pixelated-user-agent --help
 /usr/bin/pixelated-user-agent --multi-user ---something
 /usr/bin/pixelated-user-agent --multi-user ---lc /nowhere/
 /usr/bin/pixelated-user-agent --multi-user -lc /nowhere/
 /usr/bin/pixelated-user-agent --multi-user -lc /nowhere/ -p test
 /usr/bin/pixelated-user-agent --multi-user -lc /nowhere/ -p wazokazi.is
```
All these exit as expected. cool
