### ISSUE TITLE
Trailing special chars in mail addresses should be visible

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#541]
When you enter an email address that ends in a special char like ')', then this character is not displayed after one presses tab.

Example (see screenshot): foo@bar.tld)

When I want to sent this mail I get the 'problems talking to server' error message, in the logs I can find something like this:

```
2015-11-30 08:03:15 [twisted] CRITICAL something failed
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_service.py", line 92, in send_mail
    yield self.mail_sender.sendmail(mail)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_sender.py", line 52, in sendmail
    results = yield self._send_mail_to_all_recipients(mail, recipients)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_sender.py", line 68, in _send_mail_to_all_recipients
    smtp_recipient = self._create_twisted_smtp_recipient(recipient)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/services/mail_sender.py", line 96, in _create_twisted_smtp_recipient
    return User(str(recipient), NOT_NEEDED, NOT_NEEDED, NOT_NEEDED)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/mail/smtp.py", line 460, in __init__
    self.dest = Address(destination, host)
  File "/usr/share/python/pixelated-user-agent/lib/python2.7/site-packages/twisted/mail/smtp.py", line 410, in __init__
    raise AddressError, "Parse error at %r of %r" % (atl[0], (addr, atl))
twisted.mail.smtp.AddressError: Parse error at ')' of ('foo@bar.tld)', [')'])
```

**Comment by fbernitt** [comment]
Hmm, weird, can't reproduce it for the screenshot, will close it for now again
