### ISSUE TITLE
Could not decrypt encrypted message

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#574]
What
---
I received an encrypted message on a dev account from another dev account. The message had two attachments (one was the original ciphered message, the other was the gpg version) and no text.

The logs are detailed below

Logs
---
2016-01-08 17:15:57 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('user@dev.pixelated-project.org',))
2016-01-08 17:15:57 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_FOUND
2016-01-08 17:15:57 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DECRYPTED
2016-01-08 17:15:57 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_LOOKING_FOR_KEY
2016-01-08 17:15:57 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_LOOKING_FOR_KEY
2016-01-08 17:15:57 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_NOT_FOUND, ('user@dev.pixelated-project.org',))
2016-01-08 17:15:57 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('user@dev.pixelated-project.org',))
2016-01-08 17:16:05 [requests.packages.urllib3.connectionpool] INFO Starting new HTTPS connection (1): nicknym.dev.pixelated-project.org
2016-01-08 17:16:07 [requests.packages.urllib3.connectionpool] DEBUG Setting read timeout to None
2016-01-08 17:16:07 [requests.packages.urllib3.connectionpool] DEBUG "GET / HTTP/1.1" 200 1761
2016-01-08 17:16:08 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_NOT_FOUND
2016-01-08 17:16:08 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_LOOKING_FOR_KEY
2016-01-08 17:16:08 [twisted] INFO "127.0.0.1" - - [08/Jan/2016:19:16:08 +0000] "GET /tags HTTP/1.1" 200 408 "http://localhost:3333/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Vivaldi/1.0.344.37"
2016-01-08 17:16:08 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, (user2@dev.pixelated-project.org',))
2016-01-08 17:16:08 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_FOUND
2016-01-08 17:16:08 [twisted] INFO "127.0.0.1" - - [08/Jan/2016:19:16:08 +0000] "GET /mails?q=tag%3A%22inbox%22&p=1&w=25 HTTP/1.1" 200 9120 "http://localhost:3333/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Vivaldi/1.0.344.37"
2016-01-08 17:16:08 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, ('user@dev.pixelated-project.org',))
Exception in thread Thread-106:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/bwagner/.venvs/pixua/lib/python2.7/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/Users/bwagner/.venvs/pixua/lib/python2.7/site-packages/gnupg/_parsers.py", line 1506, in _handle_status
    super(Crypt, self)._handle_status(key, value)
  File "/Users/bwagner/.venvs/pixua/lib/python2.7/site-packages/gnupg/_parsers.py", line 1419, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'NEWSIG'

2016-01-08 17:16:08 [leap.keymanager.openpgp] ERROR Failed to decrypt: Failed to encrypt/decrypt: None.
2016-01-08 17:16:09 [leap.mail.incoming.service] WARNING Failed to decrypt encrypted message (Failed to encrypt/decrypt: None). Storing message without modifications.
2016-01-08 17:16:09 [leap.mail.incoming.service] DEBUG There is no url on the OpenPGP header: id=8C61F7E2C2E79404;

**Comment by re-nobre** [comment]
hey, @bwagnerr !
Do it still happen?

**Comment by bwagnerr** [comment]
@re-nobre This happens from time to time, but I still couldn't find a way to reliably reproduce this

**Comment by re-nobre** [comment]
do you think make sense invest time now on this trying to reproduce? @bwagnerr

**Comment by bwagnerr** [comment]
Nope, I don't think so considering we don't really know where to start

**Comment by re-nobre** [comment]
So, I'm closing this issue for now. 
If make sense, we can reopen it on the future. :)
