### ISSUE TITLE
Fix: key generation events should be handled separately for each account

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#587]
Currently the LeapSession of each currently logged in user listens to all key generation events, no matter to which account they belong. 

Only if a key has been generated for the current user, the account should be set to fresh

**Comment by giovaneliberato** [comment]
It works! :camel:

**Comment by giovaneliberato** [comment]
@fbernitt I got this error even after fun `./go setup` to update the libraries. Is that something else I need to do?

```
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 565, in _run_callback
    ret = callback()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vagrant/user-agent-venv/src/leap.common/src/leap/common/events/client.py", line 398, in <lambda>
    self._loop.add_callback(lambda: callback(event, *content))
```
