### ISSUE TITLE
install-pixelated.sh fails to install PhantomJS

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#597]
```
varac@leap-jessie:~/pixelated-user-agent$ ./install-pixelated.sh

/usr/bin/node
/usr/bin/npm
/usr/bin/ruby
/usr/bin/virtualenv
/usr/bin/git
/usr/bin/gpg
/usr/bin/compass
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
\
> phantomjs@1.9.19 install /home/varac/pixelated-user-agent/web-ui/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [========================================] 100% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
] killed: false, code: 2, signal: null } Error: Command failed: tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.


```

 i tried two times, and both failed at the same step.

**Comment by varac** [comment]
this is reproducible with (but make sure you are using the [latest LEAP/jessie v1.1.0 vagrant basebox](https://atlas.hashicorp.com/LEAP/boxes/jessie/versions/1.1.0) and purge all older versions first ): 

```
--- /tmp » curl https://raw.githubusercontent.com/pixelated/pixelated-user-agent/master/vagrant_setup.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   693  100   693    0     0   3431      0 --:--:-- --:--:-- --:--:--  3447
Cloning into 'pixelated-user-agent'...
remote: Counting objects: 19033, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 19033 (delta 14), reused 0 (delta 0), pack-reused 18982
Receiving objects: 100% (19033/19033), 4.44 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (14353/14353), done.
Checking connectivity... done.
Bringing machine 'source' up with 'libvirt' provider...
==> source: Creating image (snapshot of base box volume).
==> source: Creating domain with the following settings...
==> source:  -- Name:              pixelated-user-agent_source
==> source:  -- Domain type:       kvm
==> source:  -- Cpus:              1
==> source:  -- Memory:            1024M
==> source:  -- Management MAC:    
==> source:  -- Loader:            
==> source:  -- Base box:          LEAP/jessie
==> source:  -- Storage pool:      default
==> source:  -- Image:             /home/varac/vagrant/storagepool/pixelated-user-agent_source.img (10G)
==> source:  -- Volume Cache:      default
==> source:  -- Kernel:            
==> source:  -- Initrd:            
==> source:  -- Graphics Type:     vnc
==> source:  -- Graphics Port:     5900
==> source:  -- Graphics IP:       127.0.0.1
==> source:  -- Graphics Password: Not defined
==> source:  -- Video Type:        cirrus
==> source:  -- Video VRAM:        9216
==> source:  -- Keymap:            en-us
==> source:  -- INPUT:             type=mouse, bus=ps2
==> source:  -- Command line : 
==> source: Pruning invalid NFS exports. Administrator privileges will be required...
==> source: Creating shared folders metadata...
==> source: Starting domain.
==> source: Waiting for domain to get an IP address...
==> source: Waiting for SSH to become available...
    source: 
    source: Vagrant insecure key detected. Vagrant will automatically replace
    source: this with a newly generated keypair for better security.
    source: 
    source: Inserting generated public key within guest...
    source: Removing insecure key from the guest if it's present...
    source: Key inserted! Disconnecting and reconnecting using new SSH key...
==> source: Forwarding ports...
==> source: 3333 (guest) => 3333 (host) (adapter eth0)
==> source: Configuring and enabling network interfaces...
==> source: Exporting NFS shared folders...
==> source: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sun 2016-02-07 21:35:26 CET; 20h ago
  Process: 4320 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 4315 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 4320 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

Feb 07 21:35:26 rocinante systemd[1]: Starting NFS server and services...
Feb 07 21:35:26 rocinante systemd[1]: Started NFS server and services.
==> source: Mounting NFS shared folders...
==> source: Running provisioner: puppet...
==> source: Running Puppet with source.pp...
==> source: stdin: is not a tty
==> source: Notice: Compiled catalog for leap-jessie.local in environment production in 0.72 seconds
==> source: Notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x287A1542472DC0E3_packages@pixelated-project.org.asc]/ensure: defined content as '{md5}e44e50ea9e2d49080427a52ba389eb42'
==> source: Notice: /Stage[main]/Pixelated::Apt/Exec[add_pixelated_key]: Triggered 'refresh' from 1 events
==> source: Notice: /Stage[main]/Phantomjs/Exec[download_phantomjs]/returns: executed successfully
==> source: Notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]/returns: tar (child): bzip2: Cannot exec: No such file or directory
==> source: Notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]/returns: tar (child): Error is not recoverable: exiting now
==> source: Notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]/returns: /bin/tar: Child returned status 2
==> source: Notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]/returns: /bin/tar: Error is not recoverable: exiting now
==> source: Error: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]: Failed to call refresh: /bin/tar xvfj phantomjs-1.9.8.tar.bz2 returned 2 instead of one of [0]
==> source: Error: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]: /bin/tar xvfj phantomjs-1.9.8.tar.bz2 returned 2 instead of one of [0]
...
```

**Comment by mnandri** [comment]
This script is already called as part of vagrant/osx/debian setup.
There is no case where the user would have to run it on his own.
