### ISSUE TITLE
auto close session after soledad token expired (24h)

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#615]
onlogin we get a soledad token and use that for authenticating agains soledad. But that token expires and we never fetch a new one. 
When people don't log out, we never delete the session and the token expires but is reused if the user comes back later.

**Comment by cz8s** [comment]
way to test: login to dev and close the tab without logout.
Then wait 24h and try to login. You should get a error that authentication failed.
Backtrace:
```
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:09 [leap.soledad.client.api] ERROR Soledad exception when syncing!
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: *--- Failure #196 ---
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: Failure: leap.soledad.common.errors.InvalidAuthTokenError:
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: *--- End of Failure #196 ---
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:09 [pixelated.resources.login_resource] INFO Login Error for cz8s
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:09 [pixelated.resources.login_resource] INFO [Failure instance: Traceback (failur
Feb 17 13:47:09 dev1 pixelated-user-agent[30297]: ]
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:55 [leap.soledad.client.api] ERROR Soledad exception when syncing!
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: *--- Failure #205 ---
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: Failure: leap.soledad.common.errors.InvalidAuthTokenError:
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: *--- End of Failure #205 ---
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:55 [pixelated.resources.login_resource] INFO Login Error for cz8s
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: 2016-02-17 13:47:55 [pixelated.resources.login_resource] INFO [Failure instance: Traceback (failur
Feb 17 13:47:55 dev1 pixelated-user-agent[30297]: ]
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: 2016-02-17 15:04:30 [leap.soledad.client.api] ERROR Soledad exception when syncing!
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: *--- Failure #216 ---
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: Failure: leap.soledad.common.errors.InvalidAuthTokenError:
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: *--- End of Failure #216 ---
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: 2016-02-17 15:04:30 [pixelated.resources.login_resource] INFO Login Error for cz8s
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: 2016-02-17 15:04:30 [pixelated.resources.login_resource] INFO [Failure instance: Traceback (failur
Feb 17 15:04:30 dev1 pixelated-user-agent[30297]: ]
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: Unhandled error in Deferred:
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: 2016-02-17 15:05:07 [twisted] CRITICAL Unhandled error in Deferred:
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: Traceback (most recent call last):
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/ba
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self.runUntilCurrent()
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/ba
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: f(*a, **kw)
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/de
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self._startRunCallbacks(result)
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/de
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self._runCallbacks()
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: --- <exception caught here> ---
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/de
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: current.result = callback(current.result, *args, **kw)
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/mail.py", line 963, in fi
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self._ready_cb()
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/imap/account.py", line 91
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self.account = Account(store, ready_cb=lambda: d.callback(self))
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/de
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: self._startRunCallbacks(result)
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/de
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: raise AlreadyCalledError
Feb 17 15:05:07 dev1 pixelated-user-agent[30297]: twisted.internet.defer.AlreadyCalledError:
```

**Comment by cz8s** [comment]
second part not fixed:
```
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: Unhandled error in Deferred:
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: 2016-02-24 12:06:30 [twisted] CRITICAL Unhandled error in Deferred:
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: Traceback (most recent call last):
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self.runUntilCurrent()
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: f(*a, **kw)
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self._startRunCallbacks(result)
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self._runCallbacks()
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: --- <exception caught here> ---
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: current.result = callback(current.result, *args, **kw)
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/mail.py", line 963, in finish_initialization
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self._ready_cb()
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/src/leap.mail/src/leap/mail/imap/account.py", line 91, in <lambda>
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self.account = Account(store, ready_cb=lambda: d.callback(self))
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: self._startRunCallbacks(result)
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: raise AlreadyCalledError
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: twisted.internet.defer.AlreadyCalledError:
Feb 24 12:06:30 pixelated pixelated-user-agent[10062]: 2016-02-24 12:06:30 [twisted] CRITICAL
Feb 24 12:06:32 pixelated pixelated-user-agent[16546]: 2016-02-24 12:06:32 [pixelated.application] INFO Starting the API on port 8080
Feb 24 12:06:32 pixelated pixelated-user-agent[16546]: 2016-02-24 12:06:32 [pixelated.application] INFO Running the reactor
```

**Comment by cz8s** [comment]
this happend again tonight on try:
```
Feb 25 03:00:15 pixelated pixelated-user-agent[13303]: *--- Failure #1435 ---
Feb 25 03:00:15 pixelated pixelated-user-agent[13303]: Failure: leap.soledad.common.errors.InvalidAuthTokenError:
Feb 25 03:00:15 pixelated pixelated-user-agent[13303]: *--- End of Failure #1435 ---
```
But this was version 0.2~19.gbp5eecd. 
It should work now. Lets see tomorrow...

**Comment by giovaneliberato** [comment]
@cz8s can you check this for the daily tomorrow?

**Comment by cz8s** [comment]
works !
