### ISSUE TITLE
functional tests break user-agent

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#623]
when the tests on staging run, the user-agent is not accessible anymore. When I try to login, I never get an answer.
This is what the log says:
```
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: exceptions.AttributeError: 'NoneType' object has no attribute 'cursor'
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: 2016-02-22 13:17:49 [twisted] CRITICAL Unhandled Error
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: Traceback (most recent call last):
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: self._startRunCallbacks(fail)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: self._runCallbacks()
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: current.result = callback(current.result, *args, **kw)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: _inlineCallbacks(r, g, deferred)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: --- <exception caught here> ---
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: result = result.throwExceptionIntoGenerator(g)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: return g.throw(self.type, self.value, self.tb)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/sqlcipher.py", line 501, in sync
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: defer_decryption=defer_decryption)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: result = g.send(result)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/sync.py", line 107, in sync
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: target_my_gen, target_my_trans_id)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/u1db/backends/__init__.py", line 136, in validate_gen_and_trans_id
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: known_trans_id = self._get_trans_id_for_gen(generation)
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/u1db/backends/sqlite_backend.py", line 283, in _get_trans_id_for_gen
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: c = self._db_handle.cursor()
Feb 22 13:17:49 pixelated pixelated-user-agent[29814]: exceptions.AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by cz8s** [comment]
ways to reproduce: (all on staging)
* restart pixelated-server: ```systemctl restart pixelated-server```
* Login should be possible now
* run the tests:```/usr/local/bin/behave --tags @staging --tags ~@wip --no-capture -k /srv/leap/tests_custom/functional-tests/``` (on staging)
* login is not possible anymore

**Comment by cz8s** [comment]
this was fixed long ago
