### ISSUE TITLE
NoneType object has no attribute render

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#684]
i got this in `/var/log/pixelated/user-agent.log`:

```
2016-05-09T13:46:19.265199+02:00 pixelated pixelated-user-agent[19703]: 2016-05-09 13:46:19 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 586: ordinal not in range(256)
2016-05-09T13:46:19.517793+02:00 pixelated pixelated-user-agent[19703]: 2016-05-09 13:46:19 [pixelated.adapter.mailstore.body_parser] WARNING Failed to encode content for charset iso-8859-1. Ignoring invalid chars: 'latin-1' codec can't encode character u'\ufffd' in position 1204: ordinal not in range(256)
2016-05-09T13:46:30.073540+02:00 pixelated pixelated-user-agent[19703]: Unhandled Error
2016-05-09T13:46:30.073584+02:00 pixelated pixelated-user-agent[19703]: Traceback (most recent call last):
2016-05-09T13:46:30.073603+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
2016-05-09T13:46:30.073622+02:00 pixelated pixelated-user-agent[19703]: body = resrc.render(self)
2016-05-09T13:46:30.073643+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/util.py", line 138, in render
2016-05-09T13:46:30.073659+02:00 pixelated pixelated-user-agent[19703]: self.d.addCallback(self._cbChild, request).addErrback(
2016-05-09T13:46:30.073675+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
2016-05-09T13:46:30.073690+02:00 pixelated pixelated-user-agent[19703]: callbackKeywords=kw)
2016-05-09T13:46:30.073707+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
2016-05-09T13:46:30.073723+02:00 pixelated pixelated-user-agent[19703]: self._runCallbacks()
2016-05-09T13:46:30.073738+02:00 pixelated pixelated-user-agent[19703]: --- <exception caught here> ---
2016-05-09T13:46:30.073753+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2016-05-09T13:46:30.073769+02:00 pixelated pixelated-user-agent[19703]: current.result = callback(current.result, *args, **kw)
2016-05-09T13:46:30.073785+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/util.py", line 144, in _cbChild
2016-05-09T13:46:30.073801+02:00 pixelated pixelated-user-agent[19703]: request.render(resource.getChildForRequest(child, request))
2016-05-09T13:46:30.073817+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
2016-05-09T13:46:30.073833+02:00 pixelated pixelated-user-agent[19703]: body = resrc.render(self)
2016-05-09T13:46:30.073848+02:00 pixelated pixelated-user-agent[19703]: exceptions.AttributeError: 'NoneType' object has no attribute 'render'
2016-05-09T13:46:30.073898+02:00 pixelated pixelated-user-agent[19703]: 2016-05-09 13:46:30 [twisted] CRITICAL Unhandled Error
2016-05-09T13:46:30.073913+02:00 pixelated pixelated-user-agent[19703]: Traceback (most recent call last):
2016-05-09T13:46:30.073928+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
2016-05-09T13:46:30.073943+02:00 pixelated pixelated-user-agent[19703]: body = resrc.render(self)
2016-05-09T13:46:30.073958+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/util.py", line 138, in render
2016-05-09T13:46:30.073976+02:00 pixelated pixelated-user-agent[19703]: self.d.addCallback(self._cbChild, request).addErrback(
2016-05-09T13:46:30.073992+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
2016-05-09T13:46:30.074007+02:00 pixelated pixelated-user-agent[19703]: callbackKeywords=kw)
2016-05-09T13:46:30.074023+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
2016-05-09T13:46:30.074039+02:00 pixelated pixelated-user-agent[19703]: self._runCallbacks()
2016-05-09T13:46:30.074054+02:00 pixelated pixelated-user-agent[19703]: --- <exception caught here> ---
2016-05-09T13:46:30.074069+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2016-05-09T13:46:30.074110+02:00 pixelated pixelated-user-agent[19703]: current.result = callback(current.result, *args, **kw)
2016-05-09T13:46:30.074127+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/util.py", line 144, in _cbChild
2016-05-09T13:46:30.074156+02:00 pixelated pixelated-user-agent[19703]: request.render(resource.getChildForRequest(child, request))
2016-05-09T13:46:30.074404+02:00 pixelated pixelated-user-agent[19703]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
2016-05-09T13:46:30.074437+02:00 pixelated pixelated-user-agent[19703]: body = resrc.render(self)
2016-05-09T13:46:30.074453+02:00 pixelated pixelated-user-agent[19703]: exceptions.AttributeError: 'NoneType' object has no attribute 'render'

```

**Comment by deniscostadsc** [comment]
I got this problem when I was running the load test.

**Comment by shabbyrobe** [comment]
If this is during startup, it happened to me too. I contributed a "fix" with #699, but it won't solve the problem during the load test. It merely replaces the exception with a 503 code. The error happens because twisted starts responding to web requests before `RootResource` has been fully initialised.

**Comment by varac** [comment]
Why was this closed ? It still shows up in the logs.

**Comment by mnandri** [comment]
Just pushed a fix.

@shabbyrobe's idea was right, just needed to cover all cases... so i reorganized the code a bit.

**Comment by deniscostadsc** [comment]
There is no error in the logs anymore.

@mnandri it this the commit that fix it? https://github.com/pixelated/pixelated-user-agent/commit/bc82002e703118b2347c59106080da03ea69b5c8

**Comment by mnandri** [comment]
@deniscostadsc 
both commits are necessary.
I have linked them all to this issue.
