### ISSUE TITLE
segfault and trap divide error at libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#690]
interesting, `dmesg` on wazokazi shows some segfaults and trap divide errors but they seems not related to a pixelated-server restart (they happen at different times).
Nonetheless we should tackle this problem:

```
root@pixelated:/var/lib/pixelated# dmesg -T |grep user
[Wed May  4 17:07:20 2016] traps: pixelated-user-[21440] trap divide error ip:7fd20950c67e sp:7ffdaeb8fd80 error:0 in libcrypto.so.1.0.0[7fd20940e000+1cc000]
[Wed May  4 18:26:28 2016] pixelated-user-[4122]: segfault at e0 ip 00007f6a871bfe6c sp 00007ffc0e614120 error 4 in libcrypto.so.1.0.0[7f6a870d2000+1cc000]
[Wed May  4 23:25:42 2016] traps: pixelated-user-[27171] trap divide error ip:7fe9fa11667e sp:7ffc33e78f70 error:0 in libcrypto.so.1.0.0[7fe9fa018000+1cc000]
[Thu May  5 20:24:05 2016] pixelated-user-[18995]: segfault at e0 ip 00007fde880aee6c sp 00007ffea2cc6140 error 4 in libcrypto.so.1.0.0[7fde87fc1000+1cc000]
[Thu May  5 21:16:15 2016] pixelated-user-[21463]: segfault at e0 ip 00007f76aec0fe6c sp 00007f768eff9f30 error 4 in libcrypto.so.1.0.0[7f76aeb22000+1cc000]
[Thu May  5 22:02:16 2016] pixelated-user-[1821]: segfault at e0 ip 00007f75170d9e6c sp 00007ffd12d5c2d0 error 4 in libcrypto.so.1.0.0[7f7516fec000+1cc000]
[Fri May  6 13:16:18 2016] pixelated-user-[13628]: segfault at e0 ip 00007fbe55ce2e6c sp 00007ffeb6d98680 error 4 in libcrypto.so.1.0.0[7fbe55bf5000+1cc000]
[Fri May  6 18:55:45 2016] traps: pixelated-user-[10585] trap divide error ip:7fafb57d467e sp:7ffc77ca4eb0 error:0 in libcrypto.so.1.0.0[7fafb56d6000+1cc000]
[Sun May  8 14:23:46 2016] traps: pixelated-user-[11308] trap divide error ip:7f7671b8067e sp:7ffd3fcb2a40 error:0 in libcrypto.so.1.0.0[7f7671a82000+1cc000]
[Mon May  9 11:35:44 2016] traps: pixelated-user-[18844] trap divide error ip:7f795ec0567e sp:7ffe1d273290 error:0 in libcrypto.so.1.0.0[7f795eb07000+1cc000]
[Mon May  9 12:37:01 2016] traps: pixelated-user-[6437] trap divide error ip:7f304e1b667e sp:7ffdc77a1120 error:0 in libcrypto.so.1.0.0[7f304e0b8000+1cc000]
[Mon May  9 12:47:30 2016] pixelated-user-[22817]: segfault at e0 ip 00007f2767b51e6c sp 00007ffce63e12f0 error 4 in libcrypto.so.1.0.0[7f2767a64000+1cc000]
[Mon May  9 13:07:57 2016] pixelated-user-[27535]: segfault at e0 ip 00007fe641c27e6c sp 00007fe62bffbf30 error 4 in libcrypto.so.1.0.0[7fe641b3a000+1cc000]
[Mon May  9 14:54:03 2016] traps: pixelated-user-[19703] trap divide error ip:7f530e44667e sp:7ffdc3736590 error:0 in libcrypto.so.1.0.0[7f530e348000+1cc000]
[Mon May  9 14:54:48 2016] traps: pixelated-user-[25836] trap divide error ip:7f0c948fa67e sp:7f0c67ffd180 error:0 in libcrypto.so.1.0.0[7f0c947fc000+1cc000]
[Mon May  9 14:59:43 2016] traps: pixelated-user-[25852] trap divide error ip:7f9f953b167e sp:7ffdae7c5c80 error:0 in libcrypto.so.1.0.0[7f9f952b3000+1cc000]
[Mon May  9 15:41:34 2016] pixelated-user-[27908]: segfault at e0 ip 00007f3007f39e6c sp 00007fffb8433ad0 error 4 in libcrypto.so.1.0.0[7f3007e4c000+1cc000]
[Mon May  9 16:07:40 2016] pixelated-user-[5726]: segfault at e0 ip 00007f127a66de6c sp 00007f125bffbf30 error 4 in libcrypto.so.1.0.0[7f127a580000+1cc000]

```

**Comment by varac** [comment]
i catched this locally using gdb:

```
(.virtualenv) --- git/pixelated-user-agent ‹master* M› » gdb python
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
...
Reading symbols from python...(no debugging symbols found)...done.

(gdb) run /home/varac/pixelated/git/pixelated-user-agent/service/.virtualenv/bin/pixelated-user-agent --multi-user --provider dev.pixelated-project.org  --debug 2> /tmp/ua.log
Starting program: /home/varac/thoughtworks/git/pixelated-user-agent/service/.virtualenv/bin/python /home/varac/pixelated/git/pixelated-user-agent/service/.virtualenv/bin/pixelated-user-agent --multi-user --provider dev.pixelated-project.org  --debug 2> /tmp/ua.log
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeead6700 (LWP 9840)]
[New Thread 0x7fffee2d5700 (LWP 9841)]
[New Thread 0x7fffed46f700 (LWP 9842)]
[New Thread 0x7fffecc6e700 (LWP 9843)]
[New Thread 0x7fffdffff700 (LWP 9844)]
[New Thread 0x7fffdf7fe700 (LWP 9845)]
[New Thread 0x7fffdeffd700 (LWP 9846)]
[New Thread 0x7fffde7fc700 (LWP 9847)]
[New Thread 0x7fffddffb700 (LWP 9848)]
[New Thread 0x7fffdd7fa700 (LWP 9849)]
[New Thread 0x7fffdcff9700 (LWP 10123)]
[New Thread 0x7fffbffff700 (LWP 10124)]
[New Thread 0x7fffbf7fe700 (LWP 10125)]
[New Thread 0x7fffbeffd700 (LWP 10126)]
[New Thread 0x7fffbe7fc700 (LWP 10127)]
[New Thread 0x7fffbdffb700 (LWP 10128)]
[New Thread 0x7fffbd7fa700 (LWP 10129)]
[New Thread 0x7fffbcff9700 (LWP 10130)]
[New Thread 0x7fff9ffff700 (LWP 10131)]
[New Thread 0x7fff9f7fe700 (LWP 10132)]
[New Thread 0x7fff9effd700 (LWP 10133)]
[New Thread 0x7fff9e7fc700 (LWP 10135)]
[New Thread 0x7fff9dffb700 (LWP 10136)]
[New Thread 0x7fff9d7fa700 (LWP 10137)]

Thread 14 "python" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffbf7fe700 (LWP 10125)]
0x00007ffff6469fc6 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) 
(gdb) backtrace 
#0  0x00007ffff6469fc6 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff0601e90 in sqlcipher_page_cipher (ctx=ctx@entry=0x7fffb00015f8, for_ctx=<optimized out>, pgno=19, mode=1, 
    page_sz=1024, in=0x7fffb0024878 "\n\001\t", 
    out=0x7fffb00135c8 "\256\354J\031\240\301۰\342G\325ڵ\276H\224n\277\350\222\352\301\332Z\226\232&Ԝ\027a\260\372Ҳ\263ic\220\b\212\317\066\342\365\027\260\306\347\274,\331\323\364Cx\340r\352\211\316\327\334w5\035\344G\233\002\021\362\262V\v_6\026\024×\020%W\377\244\026$wNN\027\321[C\337̯\221\034\352k\302\070\364\200\021T{\346\f\205\334\004D\275\063D\003+ޱ\335\346)\006\224u\002\340\256Y0z\361\302@\215\340\036\257\027\316g\245s\340\267\364Q\310\323f*\211\224\233t\243g\253\243\367^EA\344\025\t\033\236\305S\016]K\346\026\036\001{\aR/\304L\266\037\250\337\317*\200\060l\254\267\233+\v"...) at amalgamation/sqlite3.c:14293
#2  0x00007ffff060223f in sqlite3Codec (iCtx=0x7fffb00015f8, data=0x7fffb0024878, pgno=19, mode=<optimized out>)
    at amalgamation/sqlite3.c:13450
#3  0x00007ffff05f20e3 in sqlite3PagerCodec (pPg=0x7fffb0024cb0) at amalgamation/sqlite3.c:46191
#4  walWriteOneFrame (p=p@entry=0x7fffbf7fbff0, pPage=pPage@entry=0x7fffb0024cb0, nTruncate=0, iOffset=iOffset@entry=18896)
    at amalgamation/sqlite3.c:48927
#5  0x00007ffff0623b13 in sqlite3WalFrames (sync_flags=<optimized out>, isCommit=1, nTruncate=154, pList=0x7fffb0019710, 
    szPage=<optimized out>, pWal=0x7fffb0012568) at amalgamation/sqlite3.c:49041
#6  pagerWalFrames (pPager=pPager@entry=0x7fffb0001b78, pList=<optimized out>, nTruncate=154, isCommit=isCommit@entry=1)
    at amalgamation/sqlite3.c:42282
#7  0x00007ffff062414d in sqlite3PagerCommitPhaseOne (pPager=0x7fffb0001b78, zMaster=zMaster@entry=0x0, noSync=noSync@entry=0)
    at amalgamation/sqlite3.c:45075
#8  0x00007ffff0624630 in sqlite3PagerCommitPhaseOne (noSync=0, zMaster=0x0, pPager=<optimized out>) at amalgamation/sqlite3.c:45054
#9  sqlite3BtreeCommitPhaseOne (p=0x7fffb0001658, zMaster=zMaster@entry=0x0) at amalgamation/sqlite3.c:52747
#10 0x00007ffff0627ef3 in sqlite3BtreeCommitPhaseOne (zMaster=0x0, p=<optimized out>) at amalgamation/sqlite3.c:61617
#11 vdbeCommit (p=0x7fffb0021cd8, db=0x7fffb0000fc8) at amalgamation/sqlite3.c:61608
#12 sqlite3VdbeHalt (p=p@entry=0x7fffb0021cd8) at amalgamation/sqlite3.c:62009
#13 0x00007ffff065070f in sqlite3VdbeExec (p=p@entry=0x7fffb0021cd8) at amalgamation/sqlite3.c:68010
#14 0x00007ffff06514df in sqlite3Step (p=0x7fffb0021cd8) at amalgamation/sqlite3.c:63451
#15 sqlite3_step (pStmt=pStmt@entry=0x7fffb0021cd8) at amalgamation/sqlite3.c:63524
#16 0x00007ffff05ec310 in pysqlite_step (statement=0x7fffb0021cd8, connection=connection@entry=0x7fffec3e84b8) at src/util.c:37
#17 0x00007ffff05e7fd1 in pysqlite_connection_commit (self=0x7fffec3e84b8, args=<optimized out>) at src/connection.c:509
#18 0x00000000004c9d42 in PyEval_EvalFrameEx ()
#19 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#20 0x00000000004def08 in ?? ()
#21 0x00000000004b1153 in PyObject_Call ()
#22 0x00000000004c73ec in PyEval_EvalFrameEx ()
---Type <return> to continue, or q <return> to quit---
#23 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#24 0x00000000004def08 in ?? ()
#25 0x00000000004b1153 in PyObject_Call ()
#26 0x00000000004c73ec in PyEval_EvalFrameEx ()
#27 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#28 0x00000000004def08 in ?? ()
#29 0x00000000004b1153 in PyObject_Call ()
#30 0x00000000004c73ec in PyEval_EvalFrameEx ()
#31 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#32 0x00000000004caf42 in PyEval_EvalFrameEx ()
#33 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#34 0x00000000004caf42 in PyEval_EvalFrameEx ()
#35 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#36 0x00000000004caf42 in PyEval_EvalFrameEx ()
#37 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#38 0x00000000004def08 in ?? ()
#39 0x00000000004b1153 in PyObject_Call ()
#40 0x00000000004c73ec in PyEval_EvalFrameEx ()
#41 0x00000000004ca39f in PyEval_EvalFrameEx ()
#42 0x00000000004ca39f in PyEval_EvalFrameEx ()
#43 0x00000000004c2e05 in PyEval_EvalCodeEx ()
#44 0x00000000004ded4e in ?? ()
#45 0x00000000004b1153 in PyObject_Call ()
#46 0x00000000004f4c3e in ?? ()
#47 0x00000000004b1153 in PyObject_Call ()
#48 0x00000000004ce940 in PyEval_CallObjectWithKeywords ()
#49 0x0000000000595ec2 in ?? ()
#50 0x00007ffff7bc16fa in start_thread (arg=0x7fffbf7fe700) at pthread_create.c:333
#51 0x00007ffff78f7b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

i broke it by only logging into dev.pix using the "loadtest21" user.

here are the  famous last words from useragent log:

```
'cd98323b8873d672bab02502aef80ff6'}, {'received': 155, 'total': 497}))
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc H-D258E567F9E713DC48F44CDEDFE6A05D716E89326709E6D4F0B81C39F2C88D32: e045f9833d0b4d1e9ccdf4e9d29851f3:1 156 T-4fbf435418cf425092f914b614b0e7c7
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 156, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc F-089a4ede_ff75_44a2_9d71_38673b82eb3f-05790BAC07259B3BA9BB1308F7541189D27C02EA5685B3CD4C7614D3AD9623F1: e045f9833d0b4d1e9ccdf4e9d29851f3:1 158 T-25b4198bd64d4e268227967c7a684003
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 157, 'total': 497}))
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc M-089a4ede_ff75_44a2_9d71_38673b82eb3f-05790BAC07259B3BA9BB1308F7541189D27C02EA5685B3CD4C7614D3AD9623F1: e045f9833d0b4d1e9ccdf4e9d29851f3:1 157 T-6aaff3c39e5d4ee3b5f2fdc51badb37c
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 158, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc M-089a4ede_ff75_44a2_9d71_38673b82eb3f-D2977A653B883B19F5EC0BB413E2891C30A721179F3472075F14B9C04825DCCB: e045f9833d0b4d1e9ccdf4e9d29851f3:1 160 T-18c5d9c00a6043418c5a80210caeb24a
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 159, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 160, 'total': 497}))
2016-05-17 16:15:48 [leap.soledad.client.http_target.fetch] DEBUG Sync receive status: 160/497
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc H-05790BAC07259B3BA9BB1308F7541189D27C02EA5685B3CD4C7614D3AD9623F1: e045f9833d0b4d1e9ccdf4e9d29851f3:1 159 T-039e319f93fe41b082b41aa28ca372a8
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 161, 'total': 497}))
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc H-D2977A653B883B19F5EC0BB413E2891C30A721179F3472075F14B9C04825DCCB: e045f9833d0b4d1e9ccdf4e9d29851f3:1 163 T-b5715af62df64e04af05fd8d49bf8b53
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 162, 'total': 497}))
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc F-089a4ede_ff75_44a2_9d71_38673b82eb3f-D2977A653B883B19F5EC0BB413E2891C30A721179F3472075F14B9C04825DCCB: e045f9833d0b4d1e9ccdf4e9d29851f3:1 162 T-1406a5d07c4f4a709ba10e95be86769c
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 163, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 164, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS
2016-05-17 16:15:48 [leap.soledad.client.encdecpool] DEBUG Sync decrypter pool: decrypted doc M-c38f00f1_ad44_4c8e_a8ac_77650cf53337-6C94D2D4425674B8D5AB0063755B6EA9AEF59E8286141ED8F893CA7A19DF22AE: e045f9833d0b4d1e9ccdf4e9d29851f3:1 166 T-b114f64e42b6424e8e9651bd9a70d17b
2016-05-17 16:15:48 [leap.common.events.client] DEBUG Emitting event: (SOLEDAD_SYNC_RECEIVE_STATUS, ({'userid': 'undefined', 'uuid': u'cd98323b8873d672bab02502aef80ff6'}, {'received': 165, 'total': 497}))
2016-05-17 16:15:48 [leap.common.events.server] DEBUG Publishing event: SOLEDAD_SYNC_RECEIVE_STATUS

```

**Comment by mnandri** [comment]
sometimes it doesn't break with just loadtest21, in which case you need to login in parallel loadtest23 as well...
both leap folders need to be empty when starting the server

**Comment by mnandri** [comment]
This is solved by reverting shyba's commit. 

See #693 for a real fix.

**Comment by varac** [comment]
To QA, see https://github.com/pixelated/pixelated-user-agent/issues/683#issuecomment-220269103

**Comment by bwagnerr** [comment]
This is a symptom of #683, I'll focus the work on that one and close this, shyba's commit only made the problem more apparent instead of creating it
