### ISSUE TITLE
Useragent fails on extra, unused syncid colum

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#696]
shybas bye-multithreading PR introduced a new colum ('syncid'). We needed to revert his changes, and now the useragent chokes on this extra colum when it exist in the local sqlite db:

```
2016-05-19T14:32:29.025601+02:00 pixelated pixelated-user-agent[8602]: 2016-05-19 14:32:29 [leap.soledad.client.pragmas] DEBUG SQLCIPHER: SETTING WRITE-AHEAD LOGGING
2016-05-19T14:32:29.039566+02:00 pixelated pixelated-user-agent[8602]: 2016-05-19 14:32:29 [leap.soledad.client.pragmas] DEBUG SQLCIPHER: SETTING SYNCHRONOUS NORMAL
2016-05-19T14:32:29.044031+02:00 pixelated pixelated-user-agent[8602]: Unhandled error in Deferred:
2016-05-19T14:32:29.044846+02:00 pixelated pixelated-user-agent[8602]: 2016-05-19 14:32:29 [twisted] CRITICAL Unhandled error in Deferred:
2016-05-19T14:32:29.044925+02:00 pixelated pixelated-user-agent[8602]: 2016-05-19 14:32:29 [leap.soledad.client.pragmas] DEBUG SQLCIPHER: SETTING WRITE-AHEAD LOGGING
2016-05-19T14:32:29.046422+02:00 pixelated pixelated-user-agent[8602]: Traceback (most recent call last):
2016-05-19T14:32:29.046470+02:00 pixelated pixelated-user-agent[8602]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2016-05-19T14:32:29.046487+02:00 pixelated pixelated-user-agent[8602]: self.run()
2016-05-19T14:32:29.046501+02:00 pixelated pixelated-user-agent[8602]: File "/usr/lib/python2.7/threading.py", line 763, in run
2016-05-19T14:32:29.046516+02:00 pixelated pixelated-user-agent[8602]: self.__target(*self.__args, **self.__kwargs)
2016-05-19T14:32:29.046531+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
2016-05-19T14:32:29.046550+02:00 pixelated pixelated-user-agent[8602]: task()
2016-05-19T14:32:29.046577+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
2016-05-19T14:32:29.046593+02:00 pixelated pixelated-user-agent[8602]: task()
2016-05-19T14:32:29.046608+02:00 pixelated pixelated-user-agent[8602]: --- <exception caught here> ---
2016-05-19T14:32:29.046632+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
2016-05-19T14:32:29.046649+02:00 pixelated pixelated-user-agent[8602]: result = inContext.theWork()
2016-05-19T14:32:29.046664+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
2016-05-19T14:32:29.046680+02:00 pixelated pixelated-user-agent[8602]: inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2016-05-19T14:32:29.046696+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2016-05-19T14:32:29.046712+02:00 pixelated pixelated-user-agent[8602]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
2016-05-19T14:32:29.046727+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2016-05-19T14:32:29.046742+02:00 pixelated pixelated-user-agent[8602]: return func(*args,**kw)
2016-05-19T14:32:29.046757+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 445, in _runInteraction
2016-05-19T14:32:29.046772+02:00 pixelated pixelated-user-agent[8602]: result = interaction(trans, *args, **kw)
2016-05-19T14:32:29.046788+02:00 pixelated pixelated-user-agent[8602]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 463, in _runOperation
2016-05-19T14:32:29.046803+02:00 pixelated pixelated-user-agent[8602]: trans.execute(*args, **kw)
2016-05-19T14:32:29.046818+02:00 pixelated pixelated-user-agent[8602]: pysqlcipher.dbapi2.OperationalError: table docs_received has 8 columns but 7 values were supplied
2016-05-19T14:32:29.046847+02:00 pixelated pixelated-user-agent[8602]: 2016-05-19 14:32:29 [twisted] CRITICAL



```

**Comment by bwagnerr** [comment]
We unreverted shyba's commit and that's not a problem anymore, let's close this issue
