### ISSUE TITLE
keymanager or gnupg or leap.mail : No such file or directory

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#720]
when trying to login loadtest21 on dev, there is an error during key retrieval... that keeps on going forever
see stacktrace below

To reproduce:
- remove loadtest21's soledad client folder ( or start the user-agent with leap-home to an empty folder)
- use dev.pixelated-project.org as the provider
- start the user agent
- and login
  once the sync is done (after the interstitial screen shows), you should see the stacktrace below all over the place in the log.

**Comment by mnandri** [comment]
on OSX:
```
2016-06-17 18:18:23 [twisted] INFO adding message 5000eff2-8423-47d3-9897-496696a5a522 to local db
2016-06-17 18:18:24 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 18:18:24 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 18:18:24 [leap.keymanager.openpgp] DEBUG [GNUPG:] ENC_TO A697F1A9FE2F3005 1 0
[GNUPG:] GOOD_PASSPHRASE
gpg: encrypted with 4096-bit RSA key, ID FE2F3005, created 2016-03-10
      "loadtest21@dev.pixelated-project.org <loadtest21@dev.pixelated-project.org>"
[GNUPG:] BEGIN_DECRYPTION
[GNUPG:] DECRYPTION_INFO 2 9
[GNUPG:] PLAINTEXT 62 1465940329
[GNUPG:] DECRYPTION_OKAY
[GNUPG:] GOODMDC
[GNUPG:] END_DECRYPTION

2016-06-17 18:18:24 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DECRYPTED, (u'loadtest21@dev.pixelated-project.org', '1'))
2016-06-17 18:18:24 [twisted] INFO processing decrypted doc
2016-06-17 18:18:24 [twisted] INFO maybe decrypting doc
2016-06-17 18:18:24 [leap.keymanager] DEBUG getting key for loadtest21@unstable.pixelated-project.org
2016-06-17 18:18:24 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 18:18:24 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 18:18:24 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17 18:18:24 [gnupg] ERROR [Errno 2] No such file or directory: ''
Exception in thread Thread-31572:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mnandri/.virtualenvs/pixelated/lib/python2.7/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/Users/mnandri/.virtualenvs/pixelated/lib/python2.7/site-packages/gnupg/_parsers.py", line 1419, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'NEWSIG'

2016-06-17 18:18:25 [twisted] INFO All parts inserted for msg!
2016-06-17 18:18:25 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_SAVED_LOCALLY, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 18:18:25 [twisted] INFO Deleting Incoming message: 42d731bf-4cf3-416c-87ac-14e0068c6ddd
2016-06-17 18:18:25 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_SAVED_LOCALLY, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 18:18:25 [twisted] INFO Deleting Incoming message: 44348112-d1ab-48b7-a2d5-25e7b6b3730d
2016-06-17 18:18:25 [leap.common.events.client] DEBUG Emitting event: (MAIL_UNREAD_MESSAGES, (u'cd98323b8873d672bab02502aef80ff6', '490'))
2016-06-17 18:18:25 [leap.common.events.client] DEBUG Emitting event: (MAIL_UNREAD_MESSAGES, (u'cd98323b8873d672bab02502aef80ff6', '490'))
2016-06-17 18:18:25 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DELETED_INCOMING, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 18:18:25 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 18:18:25 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 18:18:25 [leap.mail.incoming.service] INFO An error has ocurred adding attached key for loadtest21@unstable.pixelated-project.org:
2016-06-17 18:18:25 [leap.mail.incoming.service] DEBUG There is no url on the OpenPGP header: id=99EAE8E5C158ED60CC581F383E0713918B62514E;
 url="https://unstable.pixelated-project.org/key/loadtest21";
 preference="signencrypt"
```

**Comment by mnandri** [comment]
on dev (debian - jessie):
```
2016-06-17 20:21:56 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DECRYPTED, (u'loadtest21@dev.pixelated-project.org', '1'))
2016-06-17 20:21:56 [twisted] INFO processing decrypted doc
2016-06-17 20:21:56 [twisted] INFO maybe decrypting doc
2016-06-17 20:21:56 [leap.keymanager] DEBUG getting key for loadtest21@unstable.pixelated-project.org
2016-06-17 20:21:56 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:21:56 [twisted] INFO All parts inserted for msg!
2016-06-17 20:21:56 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:21:58 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17 20:21:58 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17 20:22:09 [leap.common.events.client] DEBUG Emitting event: (MAIL_UNREAD_MESSAGES, (u'cd98323b8873d672bab02502aef80ff6', '405'))
2016-06-17 20:22:15 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 20:22:15 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 20:22:15 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DELETED_INCOMING, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 20:22:15 [twisted] INFO All parts inserted for msg!
2016-06-17 20:22:15 [leap.mail.incoming.service] INFO An error has ocurred adding attached key for loadtest21@unstable.pixelated-project.org:
2016-06-17 20:22:15 [leap.mail.incoming.service] DEBUG There is no url on the OpenPGP header: id=99EAE8E5C158ED60CC581F383E0713918B62514E;
 url="https://unstable.pixelated-project.org/key/loadtest21";
 preference="signencrypt"
2016-06-17 20:22:15 [twisted] INFO adding message a73c8493-e0dd-4237-8b21-7657e1417481 to local db
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DELETED_INCOMING
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DECRYPTED
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_LOOKING_FOR_KEY
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_FOUND
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_SAVED_LOCALLY
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_UNREAD_MESSAGES
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_UNREAD_MESSAGES
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DELETED_INCOMING
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DELETED_INCOMING
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DECRYPTED
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_LOOKING_FOR_KEY
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_FOUND
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_UNREAD_MESSAGES
2016-06-17 20:22:15 [leap.common.events.server] DEBUG Publishing event: MAIL_MSG_DELETED_INCOMING
2016-06-17 20:22:15 [leap.keymanager.openpgp] DEBUG [GNUPG:] ENC_TO A697F1A9FE2F3005 1 0
[GNUPG:] GOOD_PASSPHRASE
gpg: encrypted with 4096-bit RSA key, ID FE2F3005, created 2016-03-10
      "loadtest21@dev.pixelated-project.org <loadtest21@dev.pixelated-project.org>"
[GNUPG:] BEGIN_DECRYPTION
[GNUPG:] DECRYPTION_INFO 2 9
[GNUPG:] PLAINTEXT 62 1465939403
[GNUPG:] DECRYPTION_OKAY
[GNUPG:] GOODMDC
[GNUPG:] END_DECRYPTION

2016-06-17 20:22:17 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DECRYPTED, (u'loadtest21@dev.pixelated-project.org', '1'))
2016-06-17 20:22:17 [twisted] INFO processing decrypted doc
2016-06-17 20:22:17 [twisted] INFO maybe decrypting doc
2016-06-17 20:22:17 [leap.keymanager] DEBUG getting key for loadtest21@unstable.pixelated-project.org
2016-06-17 20:22:17 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:22:17 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 20:22:17 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 20:22:17 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:22:20 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17 20:22:20 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17 20:22:31 [twisted] INFO All parts inserted for msg!
2016-06-17 20:22:31 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_SAVED_LOCALLY, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 20:22:31 [twisted] INFO Deleting Incoming message: a3fcb22e-02dc-4171-92df-78651f1360c5
2016-06-17 20:22:31 [leap.common.events.client] DEBUG Emitting event: (MAIL_UNREAD_MESSAGES, (u'cd98323b8873d672bab02502aef80ff6', '407'))
2016-06-17 20:22:36 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DELETED_INCOMING, (u'loadtest21@dev.pixelated-project.org',))
2016-06-17 20:22:36 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 20:22:36 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 20:22:37 [twisted] INFO All parts inserted for msg!
2016-06-17 20:22:37 [leap.keymanager.openpgp] DEBUG [GNUPG:] ENC_TO A697F1A9FE2F3005 1 0
[GNUPG:] GOOD_PASSPHRASE
gpg: encrypted with 4096-bit RSA key, ID FE2F3005, created 2016-03-10
      "loadtest21@dev.pixelated-project.org <loadtest21@dev.pixelated-project.org>"
[GNUPG:] BEGIN_DECRYPTION
[GNUPG:] DECRYPTION_INFO 2 9
[GNUPG:] PLAINTEXT 62 1465939311
[GNUPG:] DECRYPTION_OKAY
[GNUPG:] GOODMDC
[GNUPG:] END_DECRYPTION
```

**Comment by mnandri** [comment]
i'm guessing the confusion could be because we're serving dev on unstable... and the keymanage can't handle that scenario: leap-provider one server, user-agent another server
worth investigating!!

**Comment by mnandri** [comment]
now dev is full of things like these:
```
2016-06-17T21:27:40.906931+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:40 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:42.429360+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:42 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:42.429874+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:42 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:43.218997+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:43 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-1C31F10CBF5FE944F0DC082E43A839FB
9A2073EC1931223887D8E55E80687858', 'type': 'meta', 'hdoc': 'H-1C31F10CBF5FE944F0DC082E43A839FB9A2073EC1931223887D8E55E80687858', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:44.022344+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:44 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:44.023136+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:44 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:44.796638+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:44 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-22742F86256C3CC50AB64DBA4CEF9A51
EFA3D812DB4940129A65E51E88801C61', 'type': 'meta', 'hdoc': 'H-22742F86256C3CC50AB64DBA4CEF9A51EFA3D812DB4940129A65E51E88801C61', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:45.156812+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:45 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-3450CC965D547B76AE1A85B3B0EDF89A
459A8F21DAA277103AC8049A27F79868', 'type': 'meta', 'hdoc': 'H-3450CC965D547B76AE1A85B3B0EDF89A459A8F21DAA277103AC8049A27F79868', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:45.675543+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:45 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:45.676306+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:45 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:46.438165+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:46 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-607F0111609A5568C88A04A2EE24DAED
EB4D525A8A4274BFAB1C74C8E6CD5BC1', 'type': 'meta', 'hdoc': 'H-607F0111609A5568C88A04A2EE24DAEDEB4D525A8A4274BFAB1C74C8E6CD5BC1', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:47.143522+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:47 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:47.144081+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:47 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:48.335860+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:48 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-1EF8EE952099BAAD7E450F642B643B83
AAE7A2BA4BBD52EBC754C093116D2070', 'type': 'meta', 'hdoc': 'H-1EF8EE952099BAAD7E450F642B643B83AAE7A2BA4BBD52EBC754C093116D2070', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:48.768050+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:48 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:48.768391+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:48 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:50.348730+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:50 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:50.349360+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:50 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:51.875855+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:51 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:51.876566+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:51 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:52.973442+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:52 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-50E51003D5D2DF79D3F56098DAC7B1FC
3402791A0E1265E77077CA7968DDACE7', 'type': 'meta', 'hdoc': 'H-50E51003D5D2DF79D3F56098DAC7B1FC3402791A0E1265E77077CA7968DDACE7', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:53.018576+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:53 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-767A88F0AC6BC8651C5003C32A397CC1
BB0840162FBB28AF87F3E9E5A7263952', 'type': 'meta', 'hdoc': 'H-767A88F0AC6BC8651C5003C32A397CC1BB0840162FBB28AF87F3E9E5A7263952', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4
C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:53.320513+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:53 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:53.320965+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:53 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:54.779412+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:54 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:54.780108+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:54 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:56.572883+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:56 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:56.572903+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:56 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:57.631628+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:57 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:57.632133+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:57 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:27:58.724510+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:58 [leap.mail.mail] ERROR BUG: (please report) Null doc_id for document {'fdoc': 'F-089a4ede_ff75_44a2_9d71_38673b82eb3f-8728090CD0BBE847EC84E768AE5F4928658E95999AC70AC8272ACFBF3AA535C9', 'type': 'meta', 'hdoc': 'H-8728090CD0BBE847EC84E768AE5F4928658E95999AC70AC8272ACFBF3AA535C9', 'cdocs': ['C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85', 'C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07']}
2016-06-17T21:27:59.544846+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:59 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:27:59.544883+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:27:59 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:28:00.689561+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:28:00 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17T21:28:00.690205+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:28:00 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17T21:28:02.248338+02:00 dev1 pixelated-user-agent[8464]: 2016-06-17 21:28:02 [gnupg] ERROR [Errno 2] No such file or directory: '-'
```

**Comment by mnandri** [comment]
on a second thought...
maybe the problem is that we might have had loadtest21 user on Unstable which no longer exists... and it is trying to fetch the key for it now...
speculation!!

**Comment by kalikaneko** [comment]
it'd be worthy to investigate where those are coming from:
```
2016-06-17 18:18:24 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17 18:18:24 [gnupg] ERROR [Errno 2] No such file or directory: ''
```

which version of gpg are you using on those systems?

**Comment by olabini** [comment]
Is this something worth keeping open? Have we seen this since? Is it based on the weird scenario of switching between providers?

**Comment by tuliocasagrande** [comment]
Hello @olabini, I agree with out, it seems it's messing with the same username at dev and unstable. For instance, this excerpt of the log:

```
2016-06-17 20:21:56 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_LOOKING_FOR_KEY, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:21:56 [twisted] INFO All parts inserted for msg!
2016-06-17 20:21:56 [leap.common.events.client] DEBUG Emitting event: (KEYMANAGER_KEY_FOUND, ('loadtest21@unstable.pixelated-project.org',))
2016-06-17 20:21:58 [gnupg] ERROR [Errno 2] No such file or directory: '-'
2016-06-17 20:21:58 [gnupg] ERROR [Errno 2] No such file or directory: ''
2016-06-17 20:22:09 [leap.common.events.client] DEBUG Emitting event: (MAIL_UNREAD_MESSAGES, (u'cd98323b8873d672bab02502aef80ff6', '405'))
2016-06-17 20:22:15 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-3EDD34266B5B54F4D544698A48BFBE2AC7376802647083EC933A5ED83BC6BB85
2016-06-17 20:22:15 [leap.mail.adaptors.soledad] DEBUG Got conflict while putting C-8685C714DD977024508132F4C167FB4004E52B24551DEA0623042F9C318FFE07
2016-06-17 20:22:15 [leap.common.events.client] DEBUG Emitting event: (MAIL_MSG_DELETED_INCOMING, (u'loadtest21@dev.pixelated-project.org',))
```

I'm not sure what caused this, but can be a weird/custom/wrong installation.
@varac Have you heard about this?

**Comment by deniscostadsc** [comment]
I also agree with @olabini. So, I'm closeing this issue. If the problem shows up again, we can reopen it.
