### ISSUE TITLE
Activist mode stopped working

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#769]
After 9cdd52be577fff75830c854bd7738ee1649e7083, we started to get the following error when starting the UA in activist mode:

```
2016-08-26 13:51:43 [twisted] ERROR Traceback (most recent call last):
2016-08-26 13:51:43 [twisted] ERROR   File "/vagrant/service/pixelated/application.py", line 99, in start
2016-08-26 13:51:43 [twisted] ERROR     start_async = _start_mode(args, resource, services_factory)
2016-08-26 13:51:43 [twisted] ERROR   File "/vagrant/service/pixelated/application.py", line 128, in _start_mode
2016-08-26 13:51:43 [twisted] ERROR     deferred = _start_in_single_user_mode(args, resource, services_factory)
2016-08-26 13:51:43 [twisted] ERROR   File "/vagrant/service/pixelated/application.py", line 174, in _start_in_single_user_mode
2016-08-26 13:51:43 [twisted] ERROR     args.leap_home)
2016-08-26 13:51:43 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
2016-08-26 13:51:43 [twisted] ERROR     return _inlineCallbacks(None, gen, Deferred())
2016-08-26 13:51:43 [twisted] ERROR --- <exception caught here> ---
2016-08-26 13:51:43 [twisted] ERROR   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
2016-08-26 13:51:43 [twisted] ERROR     result = g.send(result)
2016-08-26 13:51:43 [twisted] ERROR   File "/vagrant/service/pixelated/config/leap.py", line 67, in initialize_leap_single_user
2016-08-26 13:51:43 [twisted] ERROR     config, provider = initialize_leap_provider(provider, leap_provider_cert, leap_provider_cert_fingerprint, leap_home)
2016-08-26 13:51:43 [twisted] ERROR exceptions.TypeError: 'LeapProvider' object is not iterable
```

**Comment by tuliocasagrande** [comment]
We've found the bug and it was quite simple to fix. So we decided to push the solution ASAP to have the activist mode working. 😎 

However, it seems we don't have properly tests for that. 💩  :trollface: 

We don't know what to do with this issue, but we think we should have automated tests for it ❤️

**Comment by re-nobre** [comment]
I added the tests problem on our list of problems. 
As it is not part of our priorities now, I'm closing this issue
