### ISSUE TITLE
Measure current memory usage for big attachments

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#814]
What
---
We currently suspect that memory is the problem that blocks us from doing big attachments.
We need to confirm or deny that assumption by measuring the baseline memory we use and how each step of handling attachments affect that.

Definition of done
---
Measure how much attachment size affects memory consumption and identify the components responsible for that increase.

**Comment by bwagnerr** [comment]
Hey, just to clarify, as I understand, this is a baseline measurement (without the new soledad changes), so we can understand better what we have to tackle.

**Comment by tuliocasagrande** [comment]
you're right @bwagnerr 
thank you for clarifying

**Comment by tayanefernandes** [comment]
@shyba replied @tuliocasagrande's question in the IRC:

> I think sending a mail will create a doc and sync it (upload). Receiving a mail will be a sync download operation with no crypto on soledad side (its decrypted by leap_mail). So, in the end, I think you can measure creating a doc, uploading it and downloading it back. Check the testing folder. There is a test_sync.py on the  benchmarks.
                                                                                                                        That should help you measure it. This file is also present on current develop branch, so you can run once on old and new code.

**Comment by thaissiqueira** [comment]
@bwagnerr and I are working on measure the current memory usage.
The comparison between new and old soledad version will be tested on #799 issue.
I'm planning to update the description of this issue to avoid misunderstanding. 
Any con?

**Comment by thaissiqueira** [comment]
Persistent error on soledad-server after sending 10M attachment, traceback:

```python
2016-11-23T17:41:35+0000 [-] WSGI application error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 83, in callWithContext
	    self.contexts.pop()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 521, in run
	    self.started = True
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 496, in run
	    appIterator = self.application(self.environ, self.startResponse)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/server/__init__.py", line 324, in application
	    return application(environ, start_response)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/server/gzip_middleware.py", line 34, in __call__
	    return self.app(environ, start_response)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/server/auth.py", line 286, in __call__
	    return self._app(environ, start_response)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/server/__init__.py", line 141, in __call__
	    return http_app.HTTPApp.__call__(self, environ, start_response)
	  File "/usr/lib/python2.7/dist-packages/u1db/remote/http_app.py", line 613, in __call__
	    HTTPInvocationByMethodWithBody(resource, environ, self)()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/server/__init__.py", line 219, in __call__
	    if body_getline().strip() != '[':
	  File "/usr/lib/python2.7/dist-packages/u1db/remote/http_app.py", line 93, in getline
	    chunk = self.read_chunk(self.MAXCHUNK)
	  File "/usr/lib/python2.7/dist-packages/u1db/remote/http_app.py", line 85, in read_chunk
	    data = self.rfile.read(min(self.remaining, atmost))
	  File "/usr/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 191, in read
	    return self._wrapped.read(size)
	exceptions.ValueError: I/O operation on closed file

2016-11-23T17:41:35+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 390, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 311, in runReactorWithLogging
	    reactor.run()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 798, in runUntilCurrent
	    f(*a, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/wsgi.py", line 512, in wsgiError
	    self.request.finish()
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 224, in finish
	    return http.Request.finish(self)
	  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 871, in finish
	    "Request.finish called on a request after its connection was lost; "
	exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

```

The error above causes the following error on the pixelated user-agent

```python
2016-11-23 17:34:57 [leap.soledad.client.api] ERROR got exception when syncing!
*--- Failure #12 ---
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.TimeoutError: Getting https://dev1.dev.pixelated-project.org:2323/user-3ee743c946fe9c0a4727d8fb5c6e9c92/sync-from/22a109b60e1b4c819efa0042e147f1b5 took longer than 30 seconds.>]
*--- End of Failure #12 ---

2016-11-23 17:34:57 [pixelated.resources.login_resource] ERROR Login error during thais14 services setup: [<twisted.python.failure.Failure twisted.internet.defer.TimeoutError: Getting https://dev1.dev.pixelated-project.org:2323/user-3ee743c946fe9c0a4727d8fb5c6e9c92/sync-from/22a109b60e1b4c819efa0042e147f1b5 took longer than 30 seconds.>]

```

**Comment by thaissiqueira** [comment]
We ran the user-agent on a vagrant machine with 1GB of memory, this is the server memory usage behaviour when we send a 10MB attachment:

![user-agent-memory-usage-attachment](https://cloud.githubusercontent.com/assets/13627260/20574117/321c65b8-b19a-11e6-9361-ed4f008f7d13.png)

The baseline usage with one user logged in was 383MB, the peak during sending was 887MB and after the operation memory stabilized at 758MB.

**Comment by thaissiqueira** [comment]
When sending a mail with big attachment, the sending takes more time and our front-end ajax request timeouts. To have attachments bigger than 5MB we need to solve this problem.

The timeout is defined here:
https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/js/helpers/monitored_ajax.js#L30

**Comment by thaissiqueira** [comment]
Even tough we managed to send a 10MB attachments with the changes above, it didn't arrive for the end-user (also on pixelated), next step is trying to understand where in the flow it was blocked/vanished.

**Comment by thaissiqueira** [comment]
After these findings, it is clear we have hurdles to solve to enable big attachments even before we deal with memory usage.
It is safe to assume that we have to solve the problems pointed here before memory becomes a problem, so we are wrapping this issue up (we couldn't finish a send/receive flow to even measure memory with the problems we found).

We'll create another issue to finish the exploration of those problems and reference it here.

**Comment by thaissiqueira** [comment]
For the record, these 5 and 10 MB that we mention above was used only during tests. Actually the system still dealing only with 1MB.
