### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#892]
Following the steps described [here](https://leap.se/slides/33c3/), I got this error:

```
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: 2016-12-28 13:32:32 [pixelated.resources.login_resource] ERROR Login error during denisccc services setup: 403 Client Error: Forbidden for url: https://api.example.org:4430/1/smtp_cert?address=denisccc
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: Traceback (most recent call last):
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: self._startRunCallbacks(fail)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: self._runCallbacks()
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: current.result = callback(current.result, *args, **kw)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: _inlineCallbacks(r, g, deferred)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: --- <exception caught here> ---
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: result = result.throwExceptionIntoGenerator(g)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: return g.throw(self.type, self.value, self.tb)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/leap.py", line 77, in setup
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: leap_session = yield create_leap_session(self._provider, user_auth.username, password, user_auth)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: result = result.throwExceptionIntoGenerator(g)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: return g.throw(self.type, self.value, self.tb)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/leap.py", line 41, in create_leap_session
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: leap_session = yield LeapSessionFactory(provider).create(username, password, auth)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: result = result.throwExceptionIntoGenerator(g)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: return g.throw(self.type, self.value, self.tb)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 40, in create
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: session = yield self._create_new_session(username, password, auth)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: result = g.send(result)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 59, in _create_new_session
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: smtp_client_cert = self._download_smtp_cert(auth)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 103, in _download_smtp_cert
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: return cert.cert_path()
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 256, in cert_path
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: self._download_smtp_cert()
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 272, in _download_smtp_cert
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: self.download_to(cert_path)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 300, in download_to
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: client_cert = self.download()
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/config/sessions.py", line 293, in download
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: response.raise_for_status()
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: raise HTTPError(http_error_msg, response=self)
Dec 28 13:32:32 wildebeest pixelated-user-agent[14038]: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.example.org:4430/1/smtp_cert?address=denisccc
```

**Comment by varac** [comment]
solved, this happened on a vagrant node where the `mx` service was lacking

**Comment by deniscostadsc** [comment]
❤️
