### ISSUE TITLE
Fix flaky attachments functional tests

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#972]
Our functional tests are often failing on the Attachment feature on the snap-ci.

```
Feature: Attachments # test/functional/features/attachments.feature:17
  As a user of Pixelated
  I want to download attachments of mails I received
  So that my peers are able to send me any kind of content, not just text
  Scenario: User opens a mail attachment               # test/functional/features/attachments.feature:22
    Given I have a mail with an attachment in my inbox # test/functional/features/steps/attachments.py:31
    When I open the first mail in the 'inbox'          # test/functional/features/steps/mail_list.py:67
      Assertion Failed: FAILED SUB-STEP: When I select the tag 'inbox'
      Substep info: Traceback (most recent call last):
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "test/functional/features/steps/tag_list.py", line 66, in impl
          assert success
      AssertionError
      Captured logging:
      INFO:twisted:"127.0.0.1" - - [13/Feb/2017:15:12:16 +0000] "GET /mails?q=tag%3A%22inbox%22&p=1&w=25 HTTP/1.1" 200 713 "http://localhost:8889/" "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"

    Then I see the mail has an attachment              # None

  Scenario: User uploads a mail attachment                 # test/functional/features/attachments.feature:29
    When I compose a message with                          # test/functional/features/steps/compose.py:25
      | subject          | body                                        |
      | Pixelated rocks! | You should definitely use it. Cheers, User. |
    And for the 'To' field I enter 'pixelated@friends.org' # test/functional/features/steps/compose.py:35
    And I find an attachment icon                          # test/functional/features/steps/attachments.py:61
    When I try to upload a file bigger than 5MB            # test/functional/features/steps/attachments.py:66
    Then I see an upload error message                     # test/functional/features/steps/attachments.py:75
    When I dismiss the error message                       # test/functional/features/steps/attachments.py:82
    Then It should not show the error message anymore      # test/functional/features/steps/attachments.py:90
    When I upload a valid file                             # test/functional/features/steps/attachments.py:96
      Traceback (most recent call last):
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "test/functional/features/steps/attachments.py", line 101, in upload_attachment
          attachment_list_item = find_element_by_css_selector(context, '#attachment-list-item li a')
        File "/var/snap-ci/repo/service/test/functional/features/steps/common.py", line 104, in find_element_by_css_selector
          return _wait_until_element_is_visible_by_locator(context, (By.CSS_SELECTOR, css_selector), timeout=timeout)
        File "/var/snap-ci/repo/service/test/functional/features/steps/common.py", line 64, in _wait_until_element_is_visible_by_locator
          wait.until(EC.presence_of_element_located(locator_tuple))
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
          raise TimeoutException(message, screen, stacktrace)
      TimeoutException: Message: 
      Screenshot: available via screen
      
      
      Captured logging:
      CRITICAL:twisted:Unhandled Error
      Traceback (most recent call last):
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
          why = self.lineReceived(line)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/http.py", line 1688, in lineReceived
          self.allContentReceived()
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/http.py", line 1767, in allContentReceived
          req.requestReceived(command, path, version)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/http.py", line 768, in requestReceived
          self.process()
      --- <exception caught here> ---
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/server.py", line 183, in process
          self.render(resrc)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
          body = resrc.render(self)
        File "/var/go/.venvs/pixua/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
          return m(request)
        File "/var/snap-ci/repo/service/pixelated/resources/keys_resource.py", line 43, in render_GET
          d.addCallback(finish_request)
      exceptions.AttributeError: 'NoneType' object has no attribute 'addCallback'
      
      INFO:twisted:"127.0.0.1" - - [13/Feb/2017:15:13:00 +0000] "GET /keys?search=pixelated@friends.org HTTP/1.1" 500 4602 "http://localhost:8889/" "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"
      INFO:twisted:"127.0.0.1" - - [13/Feb/2017:15:13:00 +0000] "GET /contacts?q=pixelated%40friends.org HTTP/1.1" 200 2 "http://localhost:8889/" "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"
      INFO:twisted:"127.0.0.1" - - [13/Feb/2017:15:13:03 +0000] "PUT /mails HTTP/1.1" 200 116 "http://localhost:8889/" "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"
      INFO:twisted:"127.0.0.1" - - [13/Feb/2017:15:13:22 +0000] "POST /attachment HTTP/1.1" 401 13 "http://localhost:8889/" "Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"
```

**Comment by deniscostadsc** [comment]
This problem seems solved after the migration to Circle-ci. So, I'm closing this issue.
