### ISSUE TITLE
pip list fails on wazokazi.is

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#983]
```
root@pixelated:~# pip list -vvv
...
leap.keymanager 0-unknown
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 80, in run
    self.run_listing(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 143, in run_listing
    self.output_package_listing(installed_packages)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 153, in output_package_listing
    if dist_is_editable(dist):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 367, in dist_is_editable
    req = FrozenRequirement.from_dist(dist, [])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /root/.pip/pip.log

```

I modified `/usr/lib/python2.7/dist-packages/pip/commands/list.py` to show the package name before processing it, so we know what package pip chokes on (in this case `leap-keymanager`). see `/usr/lib/python2.7/dist-packages/pip/commands/list.py.orig` for the unmodified code.

**Comment by varac** [comment]
Putting the to candidate because it currently breaks `leap deploy`.

**Comment by varac** [comment]
when I remove `leap-keymanager` it chokes at soledad-client:

```
leap.soledad.client 0.8.1-114.g57447e6.dirty
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 80, in run
    self.run_listing(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 143, in run_listing
    self.output_package_listing(installed_packages)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 153, in output_package_listing
    if dist_is_editable(dist):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 367, in dist_is_editable
    req = FrozenRequirement.from_dist(dist, [])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /root/.pip/pip.log

```

**Comment by varac** [comment]
see https://github.com/pixelated/project-issues/issues/421 and https://0xacab.org/leap/platform/issues/8754.

**Comment by varac** [comment]
`pip install --upgrade pip` fixed this.
