### ISSUE TITLE
Functional tests fail due to short timeout

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#989]
I [added timestamps to the functional test logs](https://github.com/pixelated/puppet-pixelated/commit/60c10a0c9ac8dfb7a2d4bb98daa26c1aab5433a4) and those reveal that the `When I open the email` test only waits 5 seconds before it timeouts ... ?
This seems to be very little and increasing the timeout might fix the tests reliably.

```
Feb 23 15:06:08 @staging                                                                                                                                                                      
Feb 23 15:06:08 Feature: send_mail # ../srv/leap/tests_custom/functional-tests/send_mail.feature:18                                                                                           
Feb 23 15:06:08                                                                                                                                                                               
Feb 23 15:06:08   @mail_to_myself                                                                                                                                                             
Feb 23 15:06:08   Scenario: user logs in end sends a mail to self  # ../srv/leap/tests_custom/functional-tests/send_mail.feature:21                                                           
Feb 23 15:06:08     Given I'm logged in                            # ../srv/leap/tests_custom/functional-tests/steps/account.py:39                                                            
Feb 23 15:06:21     When I send a mail to myself                   # ../srv/leap/tests_custom/functional-tests/steps/send_mail.py:28                                                          
Feb 23 15:06:22     When I open the email                          # ../srv/leap/tests_custom/functional-tests/steps/send_mail.py:41                                                          
Feb 23 15:09:26       Traceback (most recent call last):                                                                                                                                      
Feb 23 15:09:26         File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1173, in run                                                                                      
Feb 23 15:09:26           match.run(runner.context)                                                                                                                                           
Feb 23 15:09:26         File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1589, in run                                                                                      
Feb 23 15:09:26           self.func(context, *args, **kwargs)
Feb 23 15:09:26         File "/srv/leap/tests_custom/functional-tests/steps/send_mail.py", line 47, in step_impl
Feb 23 15:09:26           maillist.select_mail(email_from, subject)
Feb 23 15:09:26         File "/srv/leap/tests_custom/functional-tests/page_objects/mail_list.py", line 59, in select_mail
Feb 23 15:09:26           self._find_element_by_xpath(xpath, timeout=timeout).click()
Feb 23 15:09:26         File "/srv/leap/tests_custom/functional-tests/page_objects/base_page_object.py", line 51, in _find_element_by_xpath
Feb 23 15:09:26           self._wait_until(EC.visibility_of_element_located(locator_tuple), timeout or self.timeout)
Feb 23 15:09:26         File "/srv/leap/tests_custom/functional-tests/page_objects/base_page_object.py", line 65, in _wait_until
Feb 23 15:09:26           wait.until(condition_function)
Feb 23 15:09:26         File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
Feb 23 15:09:26           raise TimeoutException(message)
Feb 23 15:09:26       TimeoutException: Message:
Feb 23 15:09:26
```

**Comment by varac** [comment]
@thaissiqueira If i understand the timeings above right, the mail is being sent out at and is expected to show up 5s later in the inbox - this is very little time for our architecture. 
I agree that it *should* be faster but until we are there, we should increase the timeout.

**Comment by tuliocasagrande** [comment]
@varac It's actually waiting 3 minutes

```
Feb 23 15:06:22     When I open the email                          # ../srv/leap/tests_custom/functional-tests/steps/send_mail.py:41                                                          
Feb 23 15:09:26       Traceback (most recent call last):                                                                                                                                     
```

```
def select_mail(self, sender, subject, timeout=180)
```

**Comment by varac** [comment]
@tuliocasagrande true, I misinterpreted the duration of the test.
So I'll close this issue.
